version: "3"

services:
  jerry:
    build: .
    ports:
      - "9999:9999"
      - "9090:9090"
      - "9091:9091"
      - "9797:9797"
      - "9094:9094"
      - "9696:9696"
      - "9494:9494"
      - "9093:9093"
      - "9898:9898"
    restart: always
    environment:
      - INSTANCE_PRIVATE_IP=${INSTANCE_PRIVATE_IP}
      - INSTANCE_PUBLIC_IP=${INSTANCE_PUBLIC_IP}
