version: "3"

services:
  jerry:
    build: .
    ports:
      - "9999:9999"
      - "9090:9090"
      - "9091:9091"
      - "9797:9797"
      - "9094:9094"
      - "9696:9696"
      - "9494:9494"
      - "9093:9093"
    restart: always
    environment:
      - INSTANCE_PRIVATE_IP=${INSTANCE_PRIVATE_IP}
      - INSTANCE_PUBLIC_IP=${INSTANCE_PUBLIC_IP}
      - AWS_S3_ID=${AWS_S3_ID}
      - AWS_S3_SECRET=${AWS_S3_SECRET}
      - URL_MONGODB_DEV=${URL_MONGODB_DEV}
      - URL_MONGODB_PROD=${URL_MONGODB_PROD}
