const MongoClient = require("mongodb").MongoClient;
const assert = require("assert");

const url =
  "mongodb+srv://taxiconnect-test-mongo-user:epzcVtEZ39ZvawlM@cluster0.cumod.mongodb.net/test?authSource=admin&replicaSet=atlas-13sofg-shard-0&readPreference=primary&appname=MongoDB%20Compass&ssl=true";

const dbName = "Taxiconnect";

const client = new MongoClient(url, { useUnifiedTopology: true });

var refRecords = `Academia,Auasblick,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Academia,Avis,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Academia,Big Bend,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Academia,Brakwater,Windhoek,Khomas,Namibia,60,,,,,,,,,,,,,,,,,,,,
Academia,Cimbebasia,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Academia,Dorado Park,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Academia,Eros,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Academia,Eros Park,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Academia,Goreangab,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Academia,Greenwell Matongo,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Academia,Hakahana,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Academia,Havana,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Academia,Hochlandpark,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Academia,Informal settlements,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Academia,Katutura,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Academia,Khomasdal,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Academia,Kilimanjaro Informal Settlement,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Academia,Klein Windhoek,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Academia,Lafrenz Industrial,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Academia,Ludwigsdorf,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Academia,Luxury Hill,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Academia,Northern Industrial,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Academia,Okuryangava,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Academia,Olympia,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Academia,Otjomuise,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Academia,Pionierspark,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Academia,Prosperita,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Academia,Rocky Crest,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Academia,Samora Machel Constituency,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Academia,Southern Industrial Area,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Academia,Suiderhof,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Academia,Tauben Glen,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Academia,Windhoek Central / CBD,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Academia,Windhoek North,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Academia,Windhoek West,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Auasblick,Academia,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Auasblick,Avis,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Auasblick,Big Bend,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Auasblick,Brakwater,Windhoek,Khomas,Namibia,60,,,,,,,,,,,,,,,,,,,,
Auasblick,Cimbebasia,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Auasblick,Dorado Park,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Auasblick,Eros,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Auasblick,Eros Park,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Auasblick,Goreangab,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Auasblick,Greenwell Matongo,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Auasblick,Hakahana,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Auasblick,Havana,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Auasblick,Hochlandpark,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Auasblick,Informal settlements,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Auasblick,Katutura,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Auasblick,Khomasdal,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Auasblick,Kilimanjaro Informal Settlement,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Auasblick,Klein Windhoek,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Auasblick,Lafrenz Industrial,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Auasblick,Ludwigsdorf,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Auasblick,Luxury Hill,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Auasblick,Northern Industrial,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Auasblick,Okuryangava,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Auasblick,Olympia,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Auasblick,Otjomuise,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Auasblick,Pionierspark,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Auasblick,Prosperita,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Auasblick,Rocky Crest,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Auasblick,Samora Machel Constituency,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Auasblick,Southern Industrial Area,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Auasblick,Suiderhof,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Auasblick,Tauben Glen,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Auasblick,Windhoek Central / CBD,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Auasblick,Windhoek North,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Auasblick,Windhoek West,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Avis,Academia,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Avis,Auasblick,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Avis,Big Bend,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Avis,Brakwater,Windhoek,Khomas,Namibia,60,,,,,,,,,,,,,,,,,,,,
Avis,Cimbebasia,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Avis,Dorado Park,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Avis,Eros,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Avis,Eros Park,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Avis,Goreangab,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Avis,Greenwell Matongo,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Avis,Hakahana,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Avis,Havana,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Avis,Hochlandpark,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Avis,Informal settlements,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Avis,Katutura,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Avis,Khomasdal,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Avis,Kilimanjaro Informal Settlement,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Avis,Klein Windhoek,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Avis,Lafrenz Industrial,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Avis,Ludwigsdorf,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Avis,Luxury Hill,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Avis,Northern Industrial,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Avis,Okuryangava,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Avis,Olympia,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Avis,Otjomuise,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Avis,Pionierspark,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Avis,Prosperita,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Avis,Rocky Crest,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Avis,Samora Machel Constituency,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Avis,Southern Industrial Area,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Avis,Suiderhof,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Avis,Tauben Glen,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Avis,Windhoek Central / CBD,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Avis,Windhoek North,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Avis,Windhoek West,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Big Bend,Academia,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Big Bend,Auasblick,Windhoek,Khomas,Namibia,36,,,,,,,,,,,,,,,,,,,,
Big Bend,Avis,Windhoek,Khomas,Namibia,36,,,,,,,,,,,,,,,,,,,,
Big Bend,Brakwater,Windhoek,Khomas,Namibia,60,,,,,,,,,,,,,,,,,,,,
Big Bend,Cimbebasia,Windhoek,Khomas,Namibia,36,,,,,,,,,,,,,,,,,,,,
Big Bend,Dorado Park,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Big Bend,Eros,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Big Bend,Eros Park,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Big Bend,Goreangab,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Big Bend,Greenwell Matongo,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Big Bend,Hakahana,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Big Bend,Havana,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Big Bend,Hochlandpark,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Big Bend,Informal settlements,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Big Bend,Katutura,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Big Bend,Khomasdal,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Big Bend,Kilimanjaro Informal Settlement,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Big Bend,Klein Windhoek,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Big Bend,Lafrenz Industrial,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Big Bend,Ludwigsdorf,Windhoek,Khomas,Namibia,36,,,,,,,,,,,,,,,,,,,,
Big Bend,Luxury Hill,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Big Bend,Northern Industrial,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Big Bend,Okuryangava,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Big Bend,Olympia,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Big Bend,Otjomuise,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Big Bend,Pionierspark,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Big Bend,Prosperita,Windhoek,Khomas,Namibia,36,,,,,,,,,,,,,,,,,,,,
Big Bend,Rocky Crest,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Big Bend,Samora Machel Constituency,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Big Bend,Southern Industrial Area,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Big Bend,Suiderhof,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Big Bend,Tauben Glen,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Big Bend,Windhoek Central / CBD,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Big Bend,Windhoek North,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Big Bend,Windhoek West,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Brakwater,Academia,Windhoek,Khomas,Namibia,100,,,,,,,,,,,,,,,,,,,,
Brakwater,Auasblick,Windhoek,Khomas,Namibia,100,,,,,,,,,,,,,,,,,,,,
Brakwater,Avis,Windhoek,Khomas,Namibia,100,,,,,,,,,,,,,,,,,,,,
Brakwater,Big Bend,Windhoek,Khomas,Namibia,100,,,,,,,,,,,,,,,,,,,,
Brakwater,Cimbebasia,Windhoek,Khomas,Namibia,100,,,,,,,,,,,,,,,,,,,,
Brakwater,Dorado Park,Windhoek,Khomas,Namibia,100,,,,,,,,,,,,,,,,,,,,
Brakwater,Eros,Windhoek,Khomas,Namibia,100,,,,,,,,,,,,,,,,,,,,
Brakwater,Eros Park,Windhoek,Khomas,Namibia,100,,,,,,,,,,,,,,,,,,,,
Brakwater,Goreangab,Windhoek,Khomas,Namibia,100,,,,,,,,,,,,,,,,,,,,
Brakwater,Greenwell Matongo,Windhoek,Khomas,Namibia,100,,,,,,,,,,,,,,,,,,,,
Brakwater,Hakahana,Windhoek,Khomas,Namibia,100,,,,,,,,,,,,,,,,,,,,
Brakwater,Havana,Windhoek,Khomas,Namibia,100,,,,,,,,,,,,,,,,,,,,
Brakwater,Hochlandpark,Windhoek,Khomas,Namibia,100,,,,,,,,,,,,,,,,,,,,
Brakwater,Informal settlements,Windhoek,Khomas,Namibia,100,,,,,,,,,,,,,,,,,,,,
Brakwater,Katutura,Windhoek,Khomas,Namibia,100,,,,,,,,,,,,,,,,,,,,
Brakwater,Khomasdal,Windhoek,Khomas,Namibia,100,,,,,,,,,,,,,,,,,,,,
Brakwater,Kilimanjaro Informal Settlement,Windhoek,Khomas,Namibia,100,,,,,,,,,,,,,,,,,,,,
Brakwater,Klein Windhoek,Windhoek,Khomas,Namibia,100,,,,,,,,,,,,,,,,,,,,
Brakwater,Lafrenz Industrial,Windhoek,Khomas,Namibia,100,,,,,,,,,,,,,,,,,,,,
Brakwater,Ludwigsdorf,Windhoek,Khomas,Namibia,100,,,,,,,,,,,,,,,,,,,,
Brakwater,Luxury Hill,Windhoek,Khomas,Namibia,100,,,,,,,,,,,,,,,,,,,,
Brakwater,Northern Industrial,Windhoek,Khomas,Namibia,100,,,,,,,,,,,,,,,,,,,,
Brakwater,Okuryangava,Windhoek,Khomas,Namibia,100,,,,,,,,,,,,,,,,,,,,
Brakwater,Olympia,Windhoek,Khomas,Namibia,100,,,,,,,,,,,,,,,,,,,,
Brakwater,Otjomuise,Windhoek,Khomas,Namibia,100,,,,,,,,,,,,,,,,,,,,
Brakwater,Pionierspark,Windhoek,Khomas,Namibia,100,,,,,,,,,,,,,,,,,,,,
Brakwater,Prosperita,Windhoek,Khomas,Namibia,100,,,,,,,,,,,,,,,,,,,,
Brakwater,Rocky Crest,Windhoek,Khomas,Namibia,100,,,,,,,,,,,,,,,,,,,,
Brakwater,Samora Machel Constituency,Windhoek,Khomas,Namibia,100,,,,,,,,,,,,,,,,,,,,
Brakwater,Southern Industrial Area,Windhoek,Khomas,Namibia,100,,,,,,,,,,,,,,,,,,,,
Brakwater,Suiderhof,Windhoek,Khomas,Namibia,100,,,,,,,,,,,,,,,,,,,,
Brakwater,Tauben Glen,Windhoek,Khomas,Namibia,100,,,,,,,,,,,,,,,,,,,,
Brakwater,Windhoek Central / CBD,Windhoek,Khomas,Namibia,100,,,,,,,,,,,,,,,,,,,,
Brakwater,Windhoek North,Windhoek,Khomas,Namibia,100,,,,,,,,,,,,,,,,,,,,
Brakwater,Windhoek West,Windhoek,Khomas,Namibia,100,,,,,,,,,,,,,,,,,,,,
Cimbebasia,Academia,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Cimbebasia,Auasblick,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Cimbebasia,Avis,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Cimbebasia,Big Bend,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Cimbebasia,Brakwater,Windhoek,Khomas,Namibia,60,,,,,,,,,,,,,,,,,,,,
Cimbebasia,Dorado Park,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Cimbebasia,Eros,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Cimbebasia,Eros Park,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Cimbebasia,Goreangab,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Cimbebasia,Greenwell Matongo,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Cimbebasia,Hakahana,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Cimbebasia,Havana,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Cimbebasia,Hochlandpark,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Cimbebasia,Informal settlements,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Cimbebasia,Katutura,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Cimbebasia,Khomasdal,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Cimbebasia,Kilimanjaro Informal Settlement,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Cimbebasia,Klein Windhoek,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Cimbebasia,Lafrenz Industrial,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Cimbebasia,Ludwigsdorf,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Cimbebasia,Luxury Hill,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Cimbebasia,Northern Industrial,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Cimbebasia,Okuryangava,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Cimbebasia,Olympia,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Cimbebasia,Otjomuise,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Cimbebasia,Pionierspark,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Cimbebasia,Prosperita,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Cimbebasia,Rocky Crest,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Cimbebasia,Samora Machel Constituency,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Cimbebasia,Southern Industrial Area,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Cimbebasia,Suiderhof,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Cimbebasia,Tauben Glen,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Cimbebasia,Windhoek Central / CBD,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Cimbebasia,Windhoek North,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Cimbebasia,Windhoek West,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Dorado Park,Academia,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Dorado Park,Auasblick,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Dorado Park,Avis,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Dorado Park,Big Bend,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Dorado Park,Brakwater,Windhoek,Khomas,Namibia,60,,,,,,,,,,,,,,,,,,,,
Dorado Park,Cimbebasia,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Dorado Park,Eros,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Dorado Park,Eros Park,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Dorado Park,Goreangab,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Dorado Park,Greenwell Matongo,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Dorado Park,Hakahana,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Dorado Park,Havana,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Dorado Park,Hochlandpark,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Dorado Park,Informal settlements,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Dorado Park,Katutura,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Dorado Park,Khomasdal,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Dorado Park,Kilimanjaro Informal Settlement,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Dorado Park,Klein Windhoek,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Dorado Park,Lafrenz Industrial,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Dorado Park,Ludwigsdorf,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Dorado Park,Luxury Hill,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Dorado Park,Northern Industrial,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Dorado Park,Okuryangava,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Dorado Park,Olympia,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Dorado Park,Otjomuise,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Dorado Park,Pionierspark,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Dorado Park,Prosperita,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Dorado Park,Rocky Crest,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Dorado Park,Samora Machel Constituency,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Dorado Park,Southern Industrial Area,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Dorado Park,Suiderhof,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Dorado Park,Tauben Glen,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Dorado Park,Windhoek Central / CBD,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Dorado Park,Windhoek North,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Dorado Park,Windhoek West,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Eros,Academia,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Eros,Auasblick,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Eros,Avis,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Eros,Big Bend,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Eros,Brakwater,Windhoek,Khomas,Namibia,60,,,,,,,,,,,,,,,,,,,,
Eros,Cimbebasia,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Eros,Dorado Park,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Eros,Eros Park,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Eros,Goreangab,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Eros,Greenwell Matongo,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Eros,Hakahana,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Eros,Havana,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Eros,Hochlandpark,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Eros,Informal settlements,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Eros,Katutura,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Eros,Khomasdal,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Eros,Kilimanjaro Informal Settlement,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Eros,Klein Windhoek,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Eros,Lafrenz Industrial,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Eros,Ludwigsdorf,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Eros,Luxury Hill,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Eros,Northern Industrial,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Eros,Okuryangava,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Eros,Olympia,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Eros,Otjomuise,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Eros,Pionierspark,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Eros,Prosperita,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Eros,Rocky Crest,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Eros,Samora Machel Constituency,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Eros,Southern Industrial Area,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Eros,Suiderhof,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Eros,Tauben Glen,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Eros,Windhoek Central / CBD,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Eros,Windhoek North,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Eros,Windhoek West,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Eros Park,Academia,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Eros Park,Auasblick,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Eros Park,Avis,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Eros Park,Big Bend,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Eros Park,Brakwater,Windhoek,Khomas,Namibia,60,,,,,,,,,,,,,,,,,,,,
Eros Park,Cimbebasia,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Eros Park,Dorado Park,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Eros Park,Eros,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Eros Park,Goreangab,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Eros Park,Greenwell Matongo,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Eros Park,Hakahana,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Eros Park,Havana,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Eros Park,Hochlandpark,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Eros Park,Informal settlements,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Eros Park,Katutura,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Eros Park,Khomasdal,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Eros Park,Kilimanjaro Informal Settlement,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Eros Park,Klein Windhoek,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Eros Park,Lafrenz Industrial,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Eros Park,Ludwigsdorf,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Eros Park,Luxury Hill,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Eros Park,Northern Industrial,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Eros Park,Okuryangava,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Eros Park,Olympia,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Eros Park,Otjomuise,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Eros Park,Pionierspark,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Eros Park,Prosperita,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Eros Park,Rocky Crest,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Eros Park,Samora Machel Constituency,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Eros Park,Southern Industrial Area,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Eros Park,Suiderhof,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Eros Park,Tauben Glen,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Eros Park,Windhoek Central / CBD,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Eros Park,Windhoek North,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Eros Park,Windhoek West,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Goreangab,Academia,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Goreangab,Auasblick,Windhoek,Khomas,Namibia,36,,,,,,,,,,,,,,,,,,,,
Goreangab,Avis,Windhoek,Khomas,Namibia,36,,,,,,,,,,,,,,,,,,,,
Goreangab,Big Bend,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Goreangab,Brakwater,Windhoek,Khomas,Namibia,60,,,,,,,,,,,,,,,,,,,,
Goreangab,Cimbebasia,Windhoek,Khomas,Namibia,36,,,,,,,,,,,,,,,,,,,,
Goreangab,Dorado Park,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Goreangab,Eros,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Goreangab,Eros Park,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Goreangab,Greenwell Matongo,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Goreangab,Hakahana,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Goreangab,Havana,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Goreangab,Hochlandpark,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Goreangab,Informal settlements,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Goreangab,Katutura,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Goreangab,Khomasdal,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Goreangab,Kilimanjaro Informal Settlement,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Goreangab,Klein Windhoek,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Goreangab,Lafrenz Industrial,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Goreangab,Ludwigsdorf,Windhoek,Khomas,Namibia,36,,,,,,,,,,,,,,,,,,,,
Goreangab,Luxury Hill,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Goreangab,Northern Industrial,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Goreangab,Okuryangava,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Goreangab,Olympia,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Goreangab,Otjomuise,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Goreangab,Pionierspark,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Goreangab,Prosperita,Windhoek,Khomas,Namibia,36,,,,,,,,,,,,,,,,,,,,
Goreangab,Rocky Crest,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Goreangab,Samora Machel Constituency,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Goreangab,Southern Industrial Area,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Goreangab,Suiderhof,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Goreangab,Tauben Glen,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Goreangab,Windhoek Central / CBD,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Goreangab,Windhoek North,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Goreangab,Windhoek West,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Greenwell Matongo,Academia,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Greenwell Matongo,Auasblick,Windhoek,Khomas,Namibia,36,,,,,,,,,,,,,,,,,,,,
Greenwell Matongo,Avis,Windhoek,Khomas,Namibia,36,,,,,,,,,,,,,,,,,,,,
Greenwell Matongo,Big Bend,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Greenwell Matongo,Brakwater,Windhoek,Khomas,Namibia,60,,,,,,,,,,,,,,,,,,,,
Greenwell Matongo,Cimbebasia,Windhoek,Khomas,Namibia,36,,,,,,,,,,,,,,,,,,,,
Greenwell Matongo,Dorado Park,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Greenwell Matongo,Eros,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Greenwell Matongo,Eros Park,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Greenwell Matongo,Goreangab,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Greenwell Matongo,Hakahana,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Greenwell Matongo,Havana,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Greenwell Matongo,Hochlandpark,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Greenwell Matongo,Informal settlements,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Greenwell Matongo,Katutura,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Greenwell Matongo,Khomasdal,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Greenwell Matongo,Kilimanjaro Informal Settlement,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Greenwell Matongo,Klein Windhoek,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Greenwell Matongo,Lafrenz Industrial,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Greenwell Matongo,Ludwigsdorf,Windhoek,Khomas,Namibia,36,,,,,,,,,,,,,,,,,,,,
Greenwell Matongo,Luxury Hill,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Greenwell Matongo,Northern Industrial,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Greenwell Matongo,Okuryangava,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Greenwell Matongo,Olympia,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Greenwell Matongo,Otjomuise,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Greenwell Matongo,Pionierspark,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Greenwell Matongo,Prosperita,Windhoek,Khomas,Namibia,36,,,,,,,,,,,,,,,,,,,,
Greenwell Matongo,Rocky Crest,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Greenwell Matongo,Samora Machel Constituency,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Greenwell Matongo,Southern Industrial Area,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Greenwell Matongo,Suiderhof,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Greenwell Matongo,Tauben Glen,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Greenwell Matongo,Windhoek Central / CBD,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Greenwell Matongo,Windhoek North,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Greenwell Matongo,Windhoek West,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Hakahana,Academia,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Hakahana,Auasblick,Windhoek,Khomas,Namibia,36,,,,,,,,,,,,,,,,,,,,
Hakahana,Avis,Windhoek,Khomas,Namibia,36,,,,,,,,,,,,,,,,,,,,
Hakahana,Big Bend,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Hakahana,Brakwater,Windhoek,Khomas,Namibia,60,,,,,,,,,,,,,,,,,,,,
Hakahana,Cimbebasia,Windhoek,Khomas,Namibia,36,,,,,,,,,,,,,,,,,,,,
Hakahana,Dorado Park,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Hakahana,Eros,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Hakahana,Eros Park,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Hakahana,Goreangab,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Hakahana,Greenwell Matongo,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Hakahana,Havana,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Hakahana,Hochlandpark,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Hakahana,Informal settlements,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Hakahana,Katutura,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Hakahana,Khomasdal,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Hakahana,Kilimanjaro Informal Settlement,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Hakahana,Klein Windhoek,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Hakahana,Lafrenz Industrial,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Hakahana,Ludwigsdorf,Windhoek,Khomas,Namibia,36,,,,,,,,,,,,,,,,,,,,
Hakahana,Luxury Hill,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Hakahana,Northern Industrial,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Hakahana,Okuryangava,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Hakahana,Olympia,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Hakahana,Otjomuise,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Hakahana,Pionierspark,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Hakahana,Prosperita,Windhoek,Khomas,Namibia,36,,,,,,,,,,,,,,,,,,,,
Hakahana,Rocky Crest,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Hakahana,Samora Machel Constituency,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Hakahana,Southern Industrial Area,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Hakahana,Suiderhof,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Hakahana,Tauben Glen,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Hakahana,Windhoek Central / CBD,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Hakahana,Windhoek North,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Hakahana,Windhoek West,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Havana,Academia,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Havana,Auasblick,Windhoek,Khomas,Namibia,36,,,,,,,,,,,,,,,,,,,,
Havana,Avis,Windhoek,Khomas,Namibia,36,,,,,,,,,,,,,,,,,,,,
Havana,Big Bend,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Havana,Brakwater,Windhoek,Khomas,Namibia,60,,,,,,,,,,,,,,,,,,,,
Havana,Cimbebasia,Windhoek,Khomas,Namibia,36,,,,,,,,,,,,,,,,,,,,
Havana,Dorado Park,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Havana,Eros,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Havana,Eros Park,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Havana,Goreangab,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Havana,Greenwell Matongo,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Havana,Hakahana,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Havana,Hochlandpark,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Havana,Informal settlements,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Havana,Katutura,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Havana,Khomasdal,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Havana,Kilimanjaro Informal Settlement,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Havana,Klein Windhoek,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Havana,Lafrenz Industrial,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Havana,Ludwigsdorf,Windhoek,Khomas,Namibia,36,,,,,,,,,,,,,,,,,,,,
Havana,Luxury Hill,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Havana,Northern Industrial,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Havana,Okuryangava,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Havana,Olympia,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Havana,Otjomuise,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Havana,Pionierspark,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Havana,Prosperita,Windhoek,Khomas,Namibia,36,,,,,,,,,,,,,,,,,,,,
Havana,Rocky Crest,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Havana,Samora Machel Constituency,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Havana,Southern Industrial Area,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Havana,Suiderhof,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Havana,Tauben Glen,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Havana,Windhoek Central / CBD,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Havana,Windhoek North,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Havana,Windhoek West,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Hochlandpark,Academia,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Hochlandpark,Auasblick,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Hochlandpark,Avis,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Hochlandpark,Big Bend,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Hochlandpark,Brakwater,Windhoek,Khomas,Namibia,60,,,,,,,,,,,,,,,,,,,,
Hochlandpark,Cimbebasia,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Hochlandpark,Dorado Park,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Hochlandpark,Eros,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Hochlandpark,Eros Park,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Hochlandpark,Goreangab,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Hochlandpark,Greenwell Matongo,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Hochlandpark,Hakahana,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Hochlandpark,Havana,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Hochlandpark,Informal settlements,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Hochlandpark,Katutura,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Hochlandpark,Khomasdal,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Hochlandpark,Kilimanjaro Informal Settlement,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Hochlandpark,Klein Windhoek,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Hochlandpark,Lafrenz Industrial,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Hochlandpark,Ludwigsdorf,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Hochlandpark,Luxury Hill,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Hochlandpark,Northern Industrial,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Hochlandpark,Okuryangava,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Hochlandpark,Olympia,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Hochlandpark,Otjomuise,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Hochlandpark,Pionierspark,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Hochlandpark,Prosperita,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Hochlandpark,Rocky Crest,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Hochlandpark,Samora Machel Constituency,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Hochlandpark,Southern Industrial Area,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Hochlandpark,Suiderhof,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Hochlandpark,Tauben Glen,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Hochlandpark,Windhoek Central / CBD,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Hochlandpark,Windhoek North,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Hochlandpark,Windhoek West,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Informal settlements,Academia,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Informal settlements,Auasblick,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Informal settlements,Avis,Windhoek,Khomas,Namibia,36,,,,,,,,,,,,,,,,,,,,
Informal settlements,Big Bend,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Informal settlements,Brakwater,Windhoek,Khomas,Namibia,60,,,,,,,,,,,,,,,,,,,,
Informal settlements,Cimbebasia,Windhoek,Khomas,Namibia,36,,,,,,,,,,,,,,,,,,,,
Informal settlements,Dorado Park,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Informal settlements,Eros,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Informal settlements,Eros Park,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Informal settlements,Goreangab,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Informal settlements,Greenwell Matongo,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Informal settlements,Hakahana,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Informal settlements,Havana,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Informal settlements,Hochlandpark,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Informal settlements,Katutura,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Informal settlements,Khomasdal,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Informal settlements,Kilimanjaro Informal Settlement,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Informal settlements,Klein Windhoek,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Informal settlements,Lafrenz Industrial,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Informal settlements,Ludwigsdorf,Windhoek,Khomas,Namibia,36,,,,,,,,,,,,,,,,,,,,
Informal settlements,Luxury Hill,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Informal settlements,Northern Industrial,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Informal settlements,Okuryangava,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Informal settlements,Olympia,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Informal settlements,Otjomuise,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Informal settlements,Pionierspark,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Informal settlements,Prosperita,Windhoek,Khomas,Namibia,36,,,,,,,,,,,,,,,,,,,,
Informal settlements,Rocky Crest,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Informal settlements,Samora Machel Constituency,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Informal settlements,Southern Industrial Area,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Informal settlements,Suiderhof,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Informal settlements,Tauben Glen,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Informal settlements,Windhoek Central / CBD,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Informal settlements,Windhoek North,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Informal settlements,Windhoek West,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Katutura,Academia,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Katutura,Auasblick,Windhoek,Khomas,Namibia,36,,,,,,,,,,,,,,,,,,,,
Katutura,Avis,Windhoek,Khomas,Namibia,36,,,,,,,,,,,,,,,,,,,,
Katutura,Big Bend,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Katutura,Brakwater,Windhoek,Khomas,Namibia,60,,,,,,,,,,,,,,,,,,,,
Katutura,Cimbebasia,Windhoek,Khomas,Namibia,36,,,,,,,,,,,,,,,,,,,,
Katutura,Dorado Park,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Katutura,Eros,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Katutura,Eros Park,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Katutura,Goreangab,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Katutura,Greenwell Matongo,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Katutura,Hakahana,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Katutura,Havana,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Katutura,Hochlandpark,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Katutura,Informal settlements,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Katutura,Khomasdal,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Katutura,Kilimanjaro Informal Settlement,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Katutura,Klein Windhoek,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Katutura,Lafrenz Industrial,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Katutura,Ludwigsdorf,Windhoek,Khomas,Namibia,36,,,,,,,,,,,,,,,,,,,,
Katutura,Luxury Hill,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Katutura,Northern Industrial,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Katutura,Okuryangava,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Katutura,Olympia,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Katutura,Otjomuise,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Katutura,Pionierspark,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Katutura,Prosperita,Windhoek,Khomas,Namibia,36,,,,,,,,,,,,,,,,,,,,
Katutura,Rocky Crest,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Katutura,Samora Machel Constituency,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Katutura,Southern Industrial Area,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Katutura,Suiderhof,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Katutura,Tauben Glen,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Katutura,Windhoek Central / CBD,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Katutura,Windhoek North,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Katutura,Windhoek West,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Khomasdal,Academia,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Khomasdal,Auasblick,Windhoek,Khomas,Namibia,36,,,,,,,,,,,,,,,,,,,,
Khomasdal,Avis,Windhoek,Khomas,Namibia,36,,,,,,,,,,,,,,,,,,,,
Khomasdal,Big Bend,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Khomasdal,Brakwater,Windhoek,Khomas,Namibia,60,,,,,,,,,,,,,,,,,,,,
Khomasdal,Cimbebasia,Windhoek,Khomas,Namibia,36,,,,,,,,,,,,,,,,,,,,
Khomasdal,Dorado Park,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Khomasdal,Eros,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Khomasdal,Eros Park,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Khomasdal,Goreangab,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Khomasdal,Greenwell Matongo,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Khomasdal,Hakahana,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Khomasdal,Havana,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Khomasdal,Hochlandpark,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Khomasdal,Informal settlements,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Khomasdal,Katutura,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Khomasdal,Kilimanjaro Informal Settlement,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Khomasdal,Klein Windhoek,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Khomasdal,Lafrenz Industrial,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Khomasdal,Ludwigsdorf,Windhoek,Khomas,Namibia,36,,,,,,,,,,,,,,,,,,,,
Khomasdal,Luxury Hill,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Khomasdal,Northern Industrial,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Khomasdal,Okuryangava,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Khomasdal,Olympia,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Khomasdal,Otjomuise,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Khomasdal,Pionierspark,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Khomasdal,Prosperita,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Khomasdal,Rocky Crest,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Khomasdal,Samora Machel Constituency,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Khomasdal,Southern Industrial Area,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Khomasdal,Suiderhof,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Khomasdal,Tauben Glen,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Khomasdal,Windhoek Central / CBD,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Khomasdal,Windhoek North,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Khomasdal,Windhoek West,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Kilimanjaro Informal Settlement,Academia,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Kilimanjaro Informal Settlement,Auasblick,Windhoek,Khomas,Namibia,36,,,,,,,,,,,,,,,,,,,,
Kilimanjaro Informal Settlement,Avis,Windhoek,Khomas,Namibia,36,,,,,,,,,,,,,,,,,,,,
Kilimanjaro Informal Settlement,Big Bend,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Kilimanjaro Informal Settlement,Brakwater,Windhoek,Khomas,Namibia,60,,,,,,,,,,,,,,,,,,,,
Kilimanjaro Informal Settlement,Cimbebasia,Windhoek,Khomas,Namibia,36,,,,,,,,,,,,,,,,,,,,
Kilimanjaro Informal Settlement,Dorado Park,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Kilimanjaro Informal Settlement,Eros,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Kilimanjaro Informal Settlement,Eros Park,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Kilimanjaro Informal Settlement,Goreangab,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Kilimanjaro Informal Settlement,Greenwell Matongo,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Kilimanjaro Informal Settlement,Hakahana,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Kilimanjaro Informal Settlement,Havana,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Kilimanjaro Informal Settlement,Hochlandpark,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Kilimanjaro Informal Settlement,Informal settlements,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Kilimanjaro Informal Settlement,Katutura,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Kilimanjaro Informal Settlement,Khomasdal,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Kilimanjaro Informal Settlement,Klein Windhoek,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Kilimanjaro Informal Settlement,Lafrenz Industrial,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Kilimanjaro Informal Settlement,Ludwigsdorf,Windhoek,Khomas,Namibia,36,,,,,,,,,,,,,,,,,,,,
Kilimanjaro Informal Settlement,Luxury Hill,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Kilimanjaro Informal Settlement,Northern Industrial,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Kilimanjaro Informal Settlement,Okuryangava,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Kilimanjaro Informal Settlement,Olympia,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Kilimanjaro Informal Settlement,Otjomuise,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Kilimanjaro Informal Settlement,Pionierspark,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Kilimanjaro Informal Settlement,Prosperita,Windhoek,Khomas,Namibia,36,,,,,,,,,,,,,,,,,,,,
Kilimanjaro Informal Settlement,Rocky Crest,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Kilimanjaro Informal Settlement,Samora Machel Constituency,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Kilimanjaro Informal Settlement,Southern Industrial Area,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Kilimanjaro Informal Settlement,Suiderhof,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Kilimanjaro Informal Settlement,Tauben Glen,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Kilimanjaro Informal Settlement,Windhoek Central / CBD,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Kilimanjaro Informal Settlement,Windhoek North,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Kilimanjaro Informal Settlement,Windhoek West,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Klein Windhoek,Academia,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Klein Windhoek,Auasblick,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Klein Windhoek,Avis,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Klein Windhoek,Big Bend,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Klein Windhoek,Brakwater,Windhoek,Khomas,Namibia,60,,,,,,,,,,,,,,,,,,,,
Klein Windhoek,Cimbebasia,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Klein Windhoek,Dorado Park,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Klein Windhoek,Eros,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Klein Windhoek,Eros Park,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Klein Windhoek,Goreangab,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Klein Windhoek,Greenwell Matongo,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Klein Windhoek,Hakahana,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Klein Windhoek,Havana,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Klein Windhoek,Hochlandpark,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Klein Windhoek,Informal settlements,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Klein Windhoek,Katutura,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Klein Windhoek,Khomasdal,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Klein Windhoek,Kilimanjaro Informal Settlement,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Klein Windhoek,Lafrenz Industrial,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Klein Windhoek,Ludwigsdorf,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Klein Windhoek,Luxury Hill,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Klein Windhoek,Northern Industrial,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Klein Windhoek,Okuryangava,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Klein Windhoek,Olympia,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Klein Windhoek,Otjomuise,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Klein Windhoek,Pionierspark,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Klein Windhoek,Prosperita,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Klein Windhoek,Rocky Crest,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Klein Windhoek,Samora Machel Constituency,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Klein Windhoek,Southern Industrial Area,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Klein Windhoek,Suiderhof,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Klein Windhoek,Tauben Glen,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Klein Windhoek,Windhoek Central / CBD,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Klein Windhoek,Windhoek North,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Klein Windhoek,Windhoek West,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Lafrenz Industrial,Academia,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Lafrenz Industrial,Auasblick,Windhoek,Khomas,Namibia,36,,,,,,,,,,,,,,,,,,,,
Lafrenz Industrial,Avis,Windhoek,Khomas,Namibia,36,,,,,,,,,,,,,,,,,,,,
Lafrenz Industrial,Big Bend,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Lafrenz Industrial,Brakwater,Windhoek,Khomas,Namibia,60,,,,,,,,,,,,,,,,,,,,
Lafrenz Industrial,Cimbebasia,Windhoek,Khomas,Namibia,36,,,,,,,,,,,,,,,,,,,,
Lafrenz Industrial,Dorado Park,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Lafrenz Industrial,Eros,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Lafrenz Industrial,Eros Park,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Lafrenz Industrial,Goreangab,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Lafrenz Industrial,Greenwell Matongo,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Lafrenz Industrial,Hakahana,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Lafrenz Industrial,Havana,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Lafrenz Industrial,Hochlandpark,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Lafrenz Industrial,Informal settlements,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Lafrenz Industrial,Katutura,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Lafrenz Industrial,Khomasdal,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Lafrenz Industrial,Kilimanjaro Informal Settlement,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Lafrenz Industrial,Klein Windhoek,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Lafrenz Industrial,Ludwigsdorf,Windhoek,Khomas,Namibia,36,,,,,,,,,,,,,,,,,,,,
Lafrenz Industrial,Luxury Hill,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Lafrenz Industrial,Northern Industrial,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Lafrenz Industrial,Okuryangava,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Lafrenz Industrial,Olympia,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Lafrenz Industrial,Otjomuise,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Lafrenz Industrial,Pionierspark,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Lafrenz Industrial,Prosperita,Windhoek,Khomas,Namibia,36,,,,,,,,,,,,,,,,,,,,
Lafrenz Industrial,Rocky Crest,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Lafrenz Industrial,Samora Machel Constituency,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Lafrenz Industrial,Southern Industrial Area,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Lafrenz Industrial,Suiderhof,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Lafrenz Industrial,Tauben Glen,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Lafrenz Industrial,Windhoek Central / CBD,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Lafrenz Industrial,Windhoek North,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Lafrenz Industrial,Windhoek West,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Ludwigsdorf,Academia,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Ludwigsdorf,Auasblick,Windhoek,Khomas,Namibia,36,,,,,,,,,,,,,,,,,,,,
Ludwigsdorf,Avis,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Ludwigsdorf,Big Bend,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Ludwigsdorf,Brakwater,Windhoek,Khomas,Namibia,60,,,,,,,,,,,,,,,,,,,,
Ludwigsdorf,Cimbebasia,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Ludwigsdorf,Dorado Park,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Ludwigsdorf,Eros,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Ludwigsdorf,Eros Park,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Ludwigsdorf,Goreangab,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Ludwigsdorf,Greenwell Matongo,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Ludwigsdorf,Hakahana,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Ludwigsdorf,Havana,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Ludwigsdorf,Hochlandpark,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Ludwigsdorf,Informal settlements,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Ludwigsdorf,Katutura,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Ludwigsdorf,Khomasdal,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Ludwigsdorf,Kilimanjaro Informal Settlement,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Ludwigsdorf,Klein Windhoek,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Ludwigsdorf,Lafrenz Industrial,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Ludwigsdorf,Luxury Hill,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Ludwigsdorf,Northern Industrial,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Ludwigsdorf,Okuryangava,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Ludwigsdorf,Olympia,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Ludwigsdorf,Otjomuise,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Ludwigsdorf,Pionierspark,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Ludwigsdorf,Prosperita,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Ludwigsdorf,Rocky Crest,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Ludwigsdorf,Samora Machel Constituency,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Ludwigsdorf,Southern Industrial Area,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Ludwigsdorf,Suiderhof,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Ludwigsdorf,Tauben Glen,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Ludwigsdorf,Windhoek Central / CBD,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Ludwigsdorf,Windhoek North,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Ludwigsdorf,Windhoek West,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Luxury Hill,Academia,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Luxury Hill,Auasblick,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Luxury Hill,Avis,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Luxury Hill,Big Bend,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Luxury Hill,Brakwater,Windhoek,Khomas,Namibia,60,,,,,,,,,,,,,,,,,,,,
Luxury Hill,Cimbebasia,Windhoek,Khomas,Namibia,36,,,,,,,,,,,,,,,,,,,,
Luxury Hill,Dorado Park,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Luxury Hill,Eros,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Luxury Hill,Eros Park,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Luxury Hill,Goreangab,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Luxury Hill,Greenwell Matongo,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Luxury Hill,Hakahana,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Luxury Hill,Havana,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Luxury Hill,Hochlandpark,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Luxury Hill,Informal settlements,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Luxury Hill,Katutura,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Luxury Hill,Khomasdal,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Luxury Hill,Kilimanjaro Informal Settlement,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Luxury Hill,Klein Windhoek,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Luxury Hill,Lafrenz Industrial,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Luxury Hill,Ludwigsdorf,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Luxury Hill,Northern Industrial,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Luxury Hill,Okuryangava,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Luxury Hill,Olympia,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Luxury Hill,Otjomuise,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Luxury Hill,Pionierspark,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Luxury Hill,Prosperita,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Luxury Hill,Rocky Crest,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Luxury Hill,Samora Machel Constituency,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Luxury Hill,Southern Industrial Area,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Luxury Hill,Suiderhof,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Luxury Hill,Tauben Glen,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Luxury Hill,Windhoek Central / CBD,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Luxury Hill,Windhoek North,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Luxury Hill,Windhoek West,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Northern Industrial,Academia,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Northern Industrial,Auasblick,Windhoek,Khomas,Namibia,36,,,,,,,,,,,,,,,,,,,,
Northern Industrial,Avis,Windhoek,Khomas,Namibia,36,,,,,,,,,,,,,,,,,,,,
Northern Industrial,Big Bend,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Northern Industrial,Brakwater,Windhoek,Khomas,Namibia,60,,,,,,,,,,,,,,,,,,,,
Northern Industrial,Cimbebasia,Windhoek,Khomas,Namibia,36,,,,,,,,,,,,,,,,,,,,
Northern Industrial,Dorado Park,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Northern Industrial,Eros,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Northern Industrial,Eros Park,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Northern Industrial,Goreangab,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Northern Industrial,Greenwell Matongo,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Northern Industrial,Hakahana,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Northern Industrial,Havana,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Northern Industrial,Hochlandpark,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Northern Industrial,Informal settlements,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Northern Industrial,Katutura,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Northern Industrial,Khomasdal,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Northern Industrial,Kilimanjaro Informal Settlement,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Northern Industrial,Klein Windhoek,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Northern Industrial,Lafrenz Industrial,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Northern Industrial,Ludwigsdorf,Windhoek,Khomas,Namibia,36,,,,,,,,,,,,,,,,,,,,
Northern Industrial,Luxury Hill,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Northern Industrial,Okuryangava,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Northern Industrial,Olympia,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Northern Industrial,Otjomuise,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Northern Industrial,Pionierspark,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Northern Industrial,Prosperita,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Northern Industrial,Rocky Crest,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Northern Industrial,Samora Machel Constituency,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Northern Industrial,Southern Industrial Area,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Northern Industrial,Suiderhof,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Northern Industrial,Tauben Glen,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Northern Industrial,Windhoek Central / CBD,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Northern Industrial,Windhoek North,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Northern Industrial,Windhoek West,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Okuryangava,Academia,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Okuryangava,Auasblick,Windhoek,Khomas,Namibia,36,,,,,,,,,,,,,,,,,,,,
Okuryangava,Avis,Windhoek,Khomas,Namibia,36,,,,,,,,,,,,,,,,,,,,
Okuryangava,Big Bend,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Okuryangava,Brakwater,Windhoek,Khomas,Namibia,60,,,,,,,,,,,,,,,,,,,,
Okuryangava,Cimbebasia,Windhoek,Khomas,Namibia,36,,,,,,,,,,,,,,,,,,,,
Okuryangava,Dorado Park,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Okuryangava,Eros,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Okuryangava,Eros Park,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Okuryangava,Goreangab,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Okuryangava,Greenwell Matongo,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Okuryangava,Hakahana,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Okuryangava,Havana,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Okuryangava,Hochlandpark,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Okuryangava,Informal settlements,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Okuryangava,Katutura,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Okuryangava,Khomasdal,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Okuryangava,Kilimanjaro Informal Settlement,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Okuryangava,Klein Windhoek,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Okuryangava,Lafrenz Industrial,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Okuryangava,Ludwigsdorf,Windhoek,Khomas,Namibia,36,,,,,,,,,,,,,,,,,,,,
Okuryangava,Luxury Hill,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Okuryangava,Northern Industrial,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Okuryangava,Olympia,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Okuryangava,Otjomuise,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Okuryangava,Pionierspark,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Okuryangava,Prosperita,Windhoek,Khomas,Namibia,36,,,,,,,,,,,,,,,,,,,,
Okuryangava,Rocky Crest,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Okuryangava,Samora Machel Constituency,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Okuryangava,Southern Industrial Area,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Okuryangava,Suiderhof,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Okuryangava,Tauben Glen,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Okuryangava,Windhoek Central / CBD,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Okuryangava,Windhoek North,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Okuryangava,Windhoek West,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Olympia,Academia,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Olympia,Auasblick,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Olympia,Avis,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Olympia,Big Bend,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Olympia,Brakwater,Windhoek,Khomas,Namibia,60,,,,,,,,,,,,,,,,,,,,
Olympia,Cimbebasia,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Olympia,Dorado Park,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Olympia,Eros,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Olympia,Eros Park,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Olympia,Goreangab,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Olympia,Greenwell Matongo,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Olympia,Hakahana,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Olympia,Havana,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Olympia,Hochlandpark,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Olympia,Informal settlements,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Olympia,Katutura,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Olympia,Khomasdal,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Olympia,Kilimanjaro Informal Settlement,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Olympia,Klein Windhoek,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Olympia,Lafrenz Industrial,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Olympia,Ludwigsdorf,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Olympia,Luxury Hill,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Olympia,Northern Industrial,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Olympia,Okuryangava,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Olympia,Otjomuise,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Olympia,Pionierspark,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Olympia,Prosperita,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Olympia,Rocky Crest,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Olympia,Samora Machel Constituency,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Olympia,Southern Industrial Area,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Olympia,Suiderhof,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Olympia,Tauben Glen,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Olympia,Windhoek Central / CBD,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Olympia,Windhoek North,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Olympia,Windhoek West,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Otjomuise,Academia,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Otjomuise,Auasblick,Windhoek,Khomas,Namibia,36,,,,,,,,,,,,,,,,,,,,
Otjomuise,Avis,Windhoek,Khomas,Namibia,36,,,,,,,,,,,,,,,,,,,,
Otjomuise,Big Bend,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Otjomuise,Brakwater,Windhoek,Khomas,Namibia,60,,,,,,,,,,,,,,,,,,,,
Otjomuise,Cimbebasia,Windhoek,Khomas,Namibia,36,,,,,,,,,,,,,,,,,,,,
Otjomuise,Dorado Park,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Otjomuise,Eros,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Otjomuise,Eros Park,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Otjomuise,Goreangab,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Otjomuise,Greenwell Matongo,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Otjomuise,Hakahana,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Otjomuise,Havana,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Otjomuise,Hochlandpark,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Otjomuise,Informal settlements,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Otjomuise,Katutura,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Otjomuise,Khomasdal,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Otjomuise,Kilimanjaro Informal Settlement,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Otjomuise,Klein Windhoek,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Otjomuise,Lafrenz Industrial,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Otjomuise,Ludwigsdorf,Windhoek,Khomas,Namibia,36,,,,,,,,,,,,,,,,,,,,
Otjomuise,Luxury Hill,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Otjomuise,Northern Industrial,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Otjomuise,Okuryangava,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Otjomuise,Olympia,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Otjomuise,Pionierspark,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Otjomuise,Prosperita,Windhoek,Khomas,Namibia,36,,,,,,,,,,,,,,,,,,,,
Otjomuise,Rocky Crest,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Otjomuise,Samora Machel Constituency,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Otjomuise,Southern Industrial Area,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Otjomuise,Suiderhof,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Otjomuise,Tauben Glen,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Otjomuise,Windhoek Central / CBD,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Otjomuise,Windhoek North,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Otjomuise,Windhoek West,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Pionierspark,Academia,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Pionierspark,Auasblick,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Pionierspark,Avis,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Pionierspark,Big Bend,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Pionierspark,Brakwater,Windhoek,Khomas,Namibia,60,,,,,,,,,,,,,,,,,,,,
Pionierspark,Cimbebasia,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Pionierspark,Dorado Park,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Pionierspark,Eros,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Pionierspark,Eros Park,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Pionierspark,Goreangab,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Pionierspark,Greenwell Matongo,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Pionierspark,Hakahana,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Pionierspark,Havana,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Pionierspark,Hochlandpark,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Pionierspark,Informal settlements,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Pionierspark,Katutura,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Pionierspark,Khomasdal,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Pionierspark,Kilimanjaro Informal Settlement,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Pionierspark,Klein Windhoek,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Pionierspark,Lafrenz Industrial,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Pionierspark,Ludwigsdorf,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Pionierspark,Luxury Hill,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Pionierspark,Northern Industrial,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Pionierspark,Okuryangava,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Pionierspark,Olympia,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Pionierspark,Otjomuise,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Pionierspark,Prosperita,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Pionierspark,Rocky Crest,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Pionierspark,Samora Machel Constituency,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Pionierspark,Southern Industrial Area,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Pionierspark,Suiderhof,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Pionierspark,Tauben Glen,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Pionierspark,Windhoek Central / CBD,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Pionierspark,Windhoek North,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Pionierspark,Windhoek West,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Prosperita,Academia,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Prosperita,Auasblick,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Prosperita,Avis,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Prosperita,Big Bend,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Prosperita,Brakwater,Windhoek,Khomas,Namibia,60,,,,,,,,,,,,,,,,,,,,
Prosperita,Cimbebasia,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Prosperita,Dorado Park,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Prosperita,Eros,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Prosperita,Eros Park,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Prosperita,Goreangab,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Prosperita,Greenwell Matongo,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Prosperita,Hakahana,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Prosperita,Havana,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Prosperita,Hochlandpark,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Prosperita,Informal settlements,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Prosperita,Katutura,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Prosperita,Khomasdal,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Prosperita,Kilimanjaro Informal Settlement,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Prosperita,Klein Windhoek,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Prosperita,Lafrenz Industrial,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Prosperita,Ludwigsdorf,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Prosperita,Luxury Hill,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Prosperita,Northern Industrial,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Prosperita,Okuryangava,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Prosperita,Olympia,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Prosperita,Otjomuise,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Prosperita,Pionierspark,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Prosperita,Rocky Crest,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Prosperita,Samora Machel Constituency,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Prosperita,Southern Industrial Area,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Prosperita,Suiderhof,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Prosperita,Tauben Glen,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Prosperita,Windhoek Central / CBD,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Prosperita,Windhoek North,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Prosperita,Windhoek West,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Rocky Crest,Academia,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Rocky Crest,Auasblick,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Rocky Crest,Avis,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Rocky Crest,Big Bend,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Rocky Crest,Brakwater,Windhoek,Khomas,Namibia,60,,,,,,,,,,,,,,,,,,,,
Rocky Crest,Cimbebasia,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Rocky Crest,Dorado Park,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Rocky Crest,Eros,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Rocky Crest,Eros Park,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Rocky Crest,Goreangab,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Rocky Crest,Greenwell Matongo,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Rocky Crest,Hakahana,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Rocky Crest,Havana,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Rocky Crest,Hochlandpark,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Rocky Crest,Informal settlements,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Rocky Crest,Katutura,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Rocky Crest,Khomasdal,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Rocky Crest,Kilimanjaro Informal Settlement,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Rocky Crest,Klein Windhoek,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Rocky Crest,Lafrenz Industrial,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Rocky Crest,Ludwigsdorf,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Rocky Crest,Luxury Hill,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Rocky Crest,Northern Industrial,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Rocky Crest,Okuryangava,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Rocky Crest,Olympia,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Rocky Crest,Otjomuise,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Rocky Crest,Pionierspark,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Rocky Crest,Prosperita,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Rocky Crest,Samora Machel Constituency,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Rocky Crest,Southern Industrial Area,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Rocky Crest,Suiderhof,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Rocky Crest,Tauben Glen,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Rocky Crest,Windhoek Central / CBD,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Rocky Crest,Windhoek North,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Rocky Crest,Windhoek West,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Samora Machel Constituency,Academia,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Samora Machel Constituency,Auasblick,Windhoek,Khomas,Namibia,36,,,,,,,,,,,,,,,,,,,,
Samora Machel Constituency,Avis,Windhoek,Khomas,Namibia,36,,,,,,,,,,,,,,,,,,,,
Samora Machel Constituency,Big Bend,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Samora Machel Constituency,Brakwater,Windhoek,Khomas,Namibia,60,,,,,,,,,,,,,,,,,,,,
Samora Machel Constituency,Cimbebasia,Windhoek,Khomas,Namibia,36,,,,,,,,,,,,,,,,,,,,
Samora Machel Constituency,Dorado Park,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Samora Machel Constituency,Eros,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Samora Machel Constituency,Eros Park,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Samora Machel Constituency,Goreangab,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Samora Machel Constituency,Greenwell Matongo,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Samora Machel Constituency,Hakahana,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Samora Machel Constituency,Havana,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Samora Machel Constituency,Hochlandpark,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Samora Machel Constituency,Informal settlements,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Samora Machel Constituency,Katutura,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Samora Machel Constituency,Khomasdal,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Samora Machel Constituency,Kilimanjaro Informal Settlement,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Samora Machel Constituency,Klein Windhoek,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Samora Machel Constituency,Lafrenz Industrial,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Samora Machel Constituency,Ludwigsdorf,Windhoek,Khomas,Namibia,36,,,,,,,,,,,,,,,,,,,,
Samora Machel Constituency,Luxury Hill,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Samora Machel Constituency,Northern Industrial,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Samora Machel Constituency,Okuryangava,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Samora Machel Constituency,Olympia,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Samora Machel Constituency,Otjomuise,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Samora Machel Constituency,Pionierspark,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Samora Machel Constituency,Prosperita,Windhoek,Khomas,Namibia,36,,,,,,,,,,,,,,,,,,,,
Samora Machel Constituency,Rocky Crest,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Samora Machel Constituency,Southern Industrial Area,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Samora Machel Constituency,Suiderhof,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Samora Machel Constituency,Tauben Glen,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Samora Machel Constituency,Windhoek Central / CBD,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Samora Machel Constituency,Windhoek North,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Samora Machel Constituency,Windhoek West,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Southern Industrial Area,Academia,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Southern Industrial Area,Auasblick,Windhoek,Khomas,Namibia,36,,,,,,,,,,,,,,,,,,,,
Southern Industrial Area,Avis,Windhoek,Khomas,Namibia,36,,,,,,,,,,,,,,,,,,,,
Southern Industrial Area,Big Bend,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Southern Industrial Area,Brakwater,Windhoek,Khomas,Namibia,60,,,,,,,,,,,,,,,,,,,,
Southern Industrial Area,Cimbebasia,Windhoek,Khomas,Namibia,36,,,,,,,,,,,,,,,,,,,,
Southern Industrial Area,Dorado Park,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Southern Industrial Area,Eros,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Southern Industrial Area,Eros Park,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Southern Industrial Area,Goreangab,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Southern Industrial Area,Greenwell Matongo,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Southern Industrial Area,Hakahana,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Southern Industrial Area,Havana,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Southern Industrial Area,Hochlandpark,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Southern Industrial Area,Informal settlements,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Southern Industrial Area,Katutura,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Southern Industrial Area,Khomasdal,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Southern Industrial Area,Kilimanjaro Informal Settlement,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Southern Industrial Area,Klein Windhoek,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Southern Industrial Area,Lafrenz Industrial,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Southern Industrial Area,Ludwigsdorf,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Southern Industrial Area,Luxury Hill,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Southern Industrial Area,Northern Industrial,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Southern Industrial Area,Okuryangava,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Southern Industrial Area,Olympia,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Southern Industrial Area,Otjomuise,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Southern Industrial Area,Pionierspark,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Southern Industrial Area,Prosperita,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Southern Industrial Area,Rocky Crest,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Southern Industrial Area,Samora Machel Constituency,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Southern Industrial Area,Suiderhof,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Southern Industrial Area,Tauben Glen,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Southern Industrial Area,Windhoek Central / CBD,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Southern Industrial Area,Windhoek North,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Southern Industrial Area,Windhoek West,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Suiderhof,Academia,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Suiderhof,Auasblick,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Suiderhof,Avis,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Suiderhof,Big Bend,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Suiderhof,Brakwater,Windhoek,Khomas,Namibia,60,,,,,,,,,,,,,,,,,,,,
Suiderhof,Cimbebasia,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Suiderhof,Dorado Park,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Suiderhof,Eros,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Suiderhof,Eros Park,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Suiderhof,Goreangab,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Suiderhof,Greenwell Matongo,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Suiderhof,Hakahana,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Suiderhof,Havana,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Suiderhof,Hochlandpark,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Suiderhof,Informal settlements,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Suiderhof,Katutura,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Suiderhof,Khomasdal,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Suiderhof,Kilimanjaro Informal Settlement,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Suiderhof,Klein Windhoek,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Suiderhof,Lafrenz Industrial,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Suiderhof,Ludwigsdorf,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Suiderhof,Luxury Hill,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Suiderhof,Northern Industrial,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Suiderhof,Okuryangava,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Suiderhof,Olympia,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Suiderhof,Otjomuise,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Suiderhof,Pionierspark,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Suiderhof,Prosperita,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Suiderhof,Rocky Crest,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Suiderhof,Samora Machel Constituency,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Suiderhof,Southern Industrial Area,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Suiderhof,Tauben Glen,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Suiderhof,Windhoek Central / CBD,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Suiderhof,Windhoek North,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Suiderhof,Windhoek West,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Tauben Glen,Academia,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Tauben Glen,Auasblick,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Tauben Glen,Avis,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Tauben Glen,Big Bend,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Tauben Glen,Brakwater,Windhoek,Khomas,Namibia,60,,,,,,,,,,,,,,,,,,,,
Tauben Glen,Cimbebasia,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Tauben Glen,Dorado Park,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Tauben Glen,Eros,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Tauben Glen,Eros Park,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Tauben Glen,Goreangab,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Tauben Glen,Greenwell Matongo,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Tauben Glen,Hakahana,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Tauben Glen,Havana,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Tauben Glen,Hochlandpark,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Tauben Glen,Informal settlements,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Tauben Glen,Katutura,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Tauben Glen,Khomasdal,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Tauben Glen,Kilimanjaro Informal Settlement,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Tauben Glen,Klein Windhoek,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Tauben Glen,Lafrenz Industrial,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Tauben Glen,Ludwigsdorf,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Tauben Glen,Luxury Hill,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Tauben Glen,Northern Industrial,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Tauben Glen,Okuryangava,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Tauben Glen,Olympia,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Tauben Glen,Otjomuise,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Tauben Glen,Pionierspark,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Tauben Glen,Prosperita,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Tauben Glen,Rocky Crest,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Tauben Glen,Samora Machel Constituency,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Tauben Glen,Southern Industrial Area,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Tauben Glen,Suiderhof,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Tauben Glen,Windhoek Central / CBD,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Tauben Glen,Windhoek North,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Tauben Glen,Windhoek West,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Windhoek Central / CBD,Academia,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Windhoek Central / CBD,Auasblick,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Windhoek Central / CBD,Avis,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Windhoek Central / CBD,Big Bend,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Windhoek Central / CBD,Brakwater,Windhoek,Khomas,Namibia,60,,,,,,,,,,,,,,,,,,,,
Windhoek Central / CBD,Cimbebasia,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Windhoek Central / CBD,Dorado Park,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Windhoek Central / CBD,Eros,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Windhoek Central / CBD,Eros Park,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Windhoek Central / CBD,Goreangab,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Windhoek Central / CBD,Greenwell Matongo,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Windhoek Central / CBD,Hakahana,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Windhoek Central / CBD,Havana,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Windhoek Central / CBD,Hochlandpark,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Windhoek Central / CBD,Informal settlements,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Windhoek Central / CBD,Katutura,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Windhoek Central / CBD,Khomasdal,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Windhoek Central / CBD,Kilimanjaro Informal Settlement,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Windhoek Central / CBD,Klein Windhoek,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Windhoek Central / CBD,Lafrenz Industrial,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Windhoek Central / CBD,Ludwigsdorf,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Windhoek Central / CBD,Luxury Hill,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Windhoek Central / CBD,Northern Industrial,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Windhoek Central / CBD,Okuryangava,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Windhoek Central / CBD,Olympia,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Windhoek Central / CBD,Otjomuise,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Windhoek Central / CBD,Pionierspark,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Windhoek Central / CBD,Prosperita,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Windhoek Central / CBD,Rocky Crest,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Windhoek Central / CBD,Samora Machel Constituency,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Windhoek Central / CBD,Southern Industrial Area,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Windhoek Central / CBD,Suiderhof,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Windhoek Central / CBD,Tauben Glen,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Windhoek Central / CBD,Windhoek North,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Windhoek Central / CBD,Windhoek West,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Windhoek North,Academia,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Windhoek North,Auasblick,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Windhoek North,Avis,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Windhoek North,Big Bend,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Windhoek North,Brakwater,Windhoek,Khomas,Namibia,60,,,,,,,,,,,,,,,,,,,,
Windhoek North,Cimbebasia,Windhoek,Khomas,Namibia,36,,,,,,,,,,,,,,,,,,,,
Windhoek North,Dorado Park,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Windhoek North,Eros,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Windhoek North,Eros Park,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Windhoek North,Goreangab,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Windhoek North,Greenwell Matongo,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Windhoek North,Hakahana,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Windhoek North,Havana,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Windhoek North,Hochlandpark,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Windhoek North,Informal settlements,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Windhoek North,Katutura,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Windhoek North,Khomasdal,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Windhoek North,Kilimanjaro Informal Settlement,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Windhoek North,Klein Windhoek,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Windhoek North,Lafrenz Industrial,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Windhoek North,Ludwigsdorf,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Windhoek North,Luxury Hill,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Windhoek North,Northern Industrial,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Windhoek North,Okuryangava,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Windhoek North,Olympia,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Windhoek North,Otjomuise,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Windhoek North,Pionierspark,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Windhoek North,Prosperita,Windhoek,Khomas,Namibia,36,,,,,,,,,,,,,,,,,,,,
Windhoek North,Rocky Crest,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Windhoek North,Samora Machel Constituency,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Windhoek North,Southern Industrial Area,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Windhoek North,Suiderhof,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Windhoek North,Tauben Glen,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Windhoek North,Windhoek Central / CBD,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Windhoek North,Windhoek West,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Windhoek West,Academia,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Windhoek West,Auasblick,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Windhoek West,Avis,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Windhoek West,Big Bend,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Windhoek West,Brakwater,Windhoek,Khomas,Namibia,60,,,,,,,,,,,,,,,,,,,,
Windhoek West,Cimbebasia,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Windhoek West,Dorado Park,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Windhoek West,Eros,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Windhoek West,Eros Park,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Windhoek West,Goreangab,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Windhoek West,Greenwell Matongo,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Windhoek West,Hakahana,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Windhoek West,Havana,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Windhoek West,Hochlandpark,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Windhoek West,Informal settlements,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Windhoek West,Katutura,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Windhoek West,Khomasdal,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Windhoek West,Kilimanjaro Informal Settlement,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Windhoek West,Klein Windhoek,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Windhoek West,Lafrenz Industrial,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Windhoek West,Ludwigsdorf,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Windhoek West,Luxury Hill,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Windhoek West,Northern Industrial,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Windhoek West,Okuryangava,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Windhoek West,Olympia,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Windhoek West,Otjomuise,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Windhoek West,Pionierspark,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Windhoek West,Prosperita,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Windhoek West,Rocky Crest,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Windhoek West,Samora Machel Constituency,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Windhoek West,Southern Industrial Area,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Windhoek West,Suiderhof,Windhoek,Khomas,Namibia,24,,,,,,,,,,,,,,,,,,,,
Windhoek West,Tauben Glen,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Windhoek West,Windhoek Central / CBD,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,
Windhoek West,Windhoek North,Windhoek,Khomas,Namibia,12,,,,,,,,,,,,,,,,,,,,`;

client.connect(function (err) {
  if (err) throw err;

  console.log("Connected successfully to Mongo.");

  const db = client.db(dbName);
  const collection = db.collection("global_prices_to_locations_map");

  refRecords = refRecords.replace(/,,,,,,,,,,,,,,,,,,,,/g, "").split("\n");

  collection.find({}).toArray(function (err, prices) {
    //console.log(prices);
    //? For doubles with pickup suburb -> destination suburb and city
    let parentPromises = prices.map((locPrice, index) => {
      return new Promise((resCheck) => {
        //!Remove duplicates of pickup drop off and fare
        collection
          .find({
            city: locPrice.city,
            pickup_suburb: locPrice.destination_suburb,
            destination_suburb: locPrice.pickup_suburb,
            fare: locPrice.fare,
          })
          .toArray(function (err, detail) {
            if (detail !== undefined && detail.length > 1) {
              //! Found stinky duplicate - remove one
              let removeDupId = detail[0]._id;
              collection.removeOne(
                { _id: removeDupId },
                function (err, suppResult) {
                  console.log("Removed stinky duplicate.");
                }
              );
            }
          });

        //!-----

        collection
          .find({
            city: locPrice.city,
            pickup_suburb: locPrice.destination_suburb,
            destination_suburb: locPrice.pickup_suburb,
          })
          .toArray(function (err, detail) {
            if (err) {
              resCheck(false);
            }
            //...
            if (detail !== undefined && detail.length > 1) {
              //! Found duplicate
              console.log(`[${index + 1}] ------------------------`);
              console.log(detail);
              //?Check price in the reference record
              refRecords.map((refString) => {
                let tmp = {};
                refString = refString.split(",");
                tmp.country = refString[4];
                tmp.city = refString[2];
                tmp.region = refString[3];
                tmp.pickup_suburb = refString[0];
                tmp.destination_suburb = refString[1];
                tmp.fare = refString[5];
                //...
                //console.log(tmp);
                if (
                  locPrice.pickup_suburb !== false &&
                  locPrice.destination_suburb !== false &&
                  new RegExp(tmp.pickup_suburb.toUpperCase().trim(), "i").test(
                    locPrice.pickup_suburb.toUpperCase().trim()
                  ) &&
                  new RegExp(
                    tmp.destination_suburb.toUpperCase().trim(),
                    "i"
                  ).test(locPrice.destination_suburb.toUpperCase().trim())
                ) {
                  //! Find the wrong record and remove it
                  detail.map((prevRecord) => {
                    if (parseFloat(prevRecord.fare) !== parseFloat(tmp.fare)) {
                      console.log("[*] WRONG RECORD IDENTIFIED");
                      //Defective info found
                      console.log(prevRecord);
                      //! Remove it
                      collection.removeOne(
                        { _id: prevRecord._id },
                        function (err, suppResult) {
                          console.log("[OK] Remove wrong pricing data.");
                        }
                      );
                    }
                  });
                }
              });

              //...
            } //Normal
            else {
              resCheck(true);
            }
          });
      });
    });
    //...DONE
    Promise.all(parentPromises)
      .then(
        (result) => {
          console.log(result);
        },
        (error) => {
          console.log(error);
        }
      )
      .catch((error) => {
        console.log(error);
      });
  });
});
