version: "2"

services:
  graphhopper:
    image: graphhopper/graphhopper
    environment:
      JAVA_OPTS: "-Xmx1g -Xms1g"
    volumes:
      - .:/data
    ports:
      - "8987:8989"
    command: "-i africa_namibia.pbf"
volumes:
  db_data: {}
