version: "3"

services:
  redis-server:
    image: redis:latest
    restart: always

  map-service-taxiconnect:
    depends_on:
      - redis-server
    build: .
    ports:
      - "9090:9090"
    restart: always
