{
    "_dispatchInstances":{
       "_debugHookTypes":null,
       "_debugID":9323,
       "_debugIsCurrentlyTiming":false,
       "_debugNeedsRemount":false,
       "_debugOwner":{
          "_debugHookTypes":null,
          "_debugID":9321,
          "_debugIsCurrentlyTiming":false,
          "_debugNeedsRemount":false,
          "_debugOwner":[
             "FiberNode"
          ],
          "_debugSource":[
             "Object"
          ],
          "actualDuration":157,
          "actualStartTime":28249,
          "alternate":[
             "FiberNode"
          ],
          "child":[
             "Circular"
          ],
          "childExpirationTime":0,
          "dependencies":null,
          "effectTag":5,
          "elementType":[
             "Function ScrollView"
          ],
          "expirationTime":0,
          "firstEffect":[
             "FiberNode"
          ],
          "index":0,
          "key":null,
          "lastEffect":[
             "Circular"
          ],
          "memoizedProps":[
             "Object"
          ],
          "memoizedState":[
             "Object"
          ],
          "mode":8,
          "nextEffect":null,
          "pendingProps":[
             "Object"
          ],
          "ref":null,
          "return":[
             "FiberNode"
          ],
          "selfBaseDuration":5,
          "sibling":null,
          "stateNode":[
             "ScrollView"
          ],
          "tag":1,
          "treeBaseDuration":63,
          "type":[
             "Function ScrollView"
          ],
          "updateQueue":[
             "Object"
          ]
       },
       "_debugSource":{
          "columnNumber":7,
          "fileName":"C:\\Users\\Dominique\\Documents\\dev-l\\TaxiApp_David\\Experiments\\TC_experience_2020\\Map\\node_modules\\react-native\\Libraries\\Components\\ScrollView\\ScrollView.js",
          "lineNumber":1260
       },
       "actualDuration":152,
       "actualStartTime":28254,
       "alternate":{
          "_debugHookTypes":null,
          "_debugID":9323,
          "_debugIsCurrentlyTiming":false,
          "_debugNeedsRemount":false,
          "_debugOwner":[
             "FiberNode"
          ],
          "_debugSource":[
             "Object"
          ],
          "actualDuration":43,
          "actualStartTime":103312,
          "alternate":[
             "Circular"
          ],
          "child":[
             "FiberNode"
          ],
          "childExpirationTime":0,
          "dependencies":null,
          "effectTag":4,
          "elementType":"AndroidHorizontalScrollView",
          "expirationTime":0,
          "firstEffect":[
             "FiberNode"
          ],
          "index":0,
          "key":null,
          "lastEffect":[
             "FiberNode"
          ],
          "memoizedProps":[
             "Object"
          ],
          "memoizedState":null,
          "mode":8,
          "nextEffect":null,
          "pendingProps":[
             "Object"
          ],
          "ref":[
             "Function forwardRef"
          ],
          "return":[
             "FiberNode"
          ],
          "selfBaseDuration":0,
          "sibling":null,
          "stateNode":[
             "ReactNativeFiberHostComponent"
          ],
          "tag":5,
          "treeBaseDuration":43,
          "type":"AndroidHorizontalScrollView",
          "updateQueue":null
       },
       "child":{
          "_debugHookTypes":null,
          "_debugID":9325,
          "_debugIsCurrentlyTiming":false,
          "_debugNeedsRemount":false,
          "_debugOwner":[
             "FiberNode"
          ],
          "_debugSource":[
             "Object"
          ],
          "actualDuration":143,
          "actualStartTime":28254,
          "alternate":[
             "FiberNode"
          ],
          "child":[
             "FiberNode"
          ],
          "childExpirationTime":0,
          "dependencies":null,
          "effectTag":128,
          "elementType":"AndroidHorizontalScrollContentView",
          "expirationTime":0,
          "firstEffect":[
             "FiberNode"
          ],
          "index":0,
          "key":null,
          "lastEffect":[
             "FiberNode"
          ],
          "memoizedProps":[
             "Object"
          ],
          "memoizedState":null,
          "mode":8,
          "nextEffect":null,
          "pendingProps":[
             "Object"
          ],
          "ref":[
             "Function forwardRef"
          ],
          "return":[
             "Circular"
          ],
          "selfBaseDuration":0,
          "sibling":null,
          "stateNode":[
             "ReactNativeFiberHostComponent"
          ],
          "tag":5,
          "treeBaseDuration":58,
          "type":"AndroidHorizontalScrollContentView",
          "updateQueue":null
       },
       "childExpirationTime":0,
       "dependencies":null,
       "effectTag":128,
       "elementType":"AndroidHorizontalScrollView",
       "expirationTime":0,
       "firstEffect":{
          "_debugHookTypes":null,
          "_debugID":9365,
          "_debugIsCurrentlyTiming":false,
          "_debugNeedsRemount":false,
          "_debugOwner":[
             "FiberNode"
          ],
          "_debugSource":[
             "Object"
          ],
          "actualDuration":25,
          "actualStartTime":28261,
          "alternate":[
             "FiberNode"
          ],
          "child":[
             "FiberNode"
          ],
          "childExpirationTime":0,
          "dependencies":null,
          "effectTag":128,
          "elementType":"RCTView",
          "expirationTime":0,
          "firstEffect":null,
          "index":0,
          "key":null,
          "lastEffect":null,
          "memoizedProps":[
             "Object"
          ],
          "memoizedState":null,
          "mode":8,
          "nextEffect":null,
          "pendingProps":[
             "Object"
          ],
          "ref":[
             "Function forwardRef"
          ],
          "return":[
             "FiberNode"
          ],
          "selfBaseDuration":0,
          "sibling":null,
          "stateNode":[
             "ReactNativeFiberHostComponent"
          ],
          "tag":5,
          "treeBaseDuration":9,
          "type":"RCTView",
          "updateQueue":null
       },
       "index":0,
       "key":null,
       "lastEffect":{
          "_debugHookTypes":null,
          "_debugID":9325,
          "_debugIsCurrentlyTiming":false,
          "_debugNeedsRemount":false,
          "_debugOwner":[
             "FiberNode"
          ],
          "_debugSource":[
             "Object"
          ],
          "actualDuration":143,
          "actualStartTime":28254,
          "alternate":[
             "FiberNode"
          ],
          "child":[
             "FiberNode"
          ],
          "childExpirationTime":0,
          "dependencies":null,
          "effectTag":128,
          "elementType":"AndroidHorizontalScrollContentView",
          "expirationTime":0,
          "firstEffect":[
             "FiberNode"
          ],
          "index":0,
          "key":null,
          "lastEffect":[
             "FiberNode"
          ],
          "memoizedProps":[
             "Object"
          ],
          "memoizedState":null,
          "mode":8,
          "nextEffect":null,
          "pendingProps":[
             "Object"
          ],
          "ref":[
             "Function forwardRef"
          ],
          "return":[
             "Circular"
          ],
          "selfBaseDuration":0,
          "sibling":null,
          "stateNode":[
             "ReactNativeFiberHostComponent"
          ],
          "tag":5,
          "treeBaseDuration":58,
          "type":"AndroidHorizontalScrollContentView",
          "updateQueue":null
       },
       "memoizedProps":{
          "DEPRECATED_sendUpdatedChildFrames":false,
          "alwaysBounceHorizontal":true,
          "alwaysBounceVertical":false,
          "children":"<AndroidHorizontalScrollContentView … />",
          "decelerationRate":0.9,
          "horizontal":true,
          "onContentSizeChange":null,
          "onLayout":[
             "Function anonymous"
          ],
          "onMomentumScrollBegin":[
             "Function bound scrollResponderHandleMomentumScrollBegin"
          ],
          "onMomentumScrollEnd":[
             "Function bound scrollResponderHandleMomentumScrollEnd"
          ],
          "onResponderGrant":[
             "Function bound scrollResponderHandleResponderGrant"
          ],
          "onResponderReject":[
             "Function bound scrollResponderHandleResponderReject"
          ],
          "onResponderRelease":[
             "Function bound scrollResponderHandleResponderRelease"
          ],
          "onResponderTerminationRequest":[
             "Function bound scrollResponderHandleTerminationRequest"
          ],
          "onScroll":[
             "Function anonymous"
          ],
          "onScrollBeginDrag":[
             "Function bound scrollResponderHandleScrollBeginDrag"
          ],
          "onScrollEndDrag":[
             "Function bound scrollResponderHandleScrollEndDrag"
          ],
          "onScrollShouldSetResponder":[
             "Function bound scrollResponderHandleScrollShouldSetResponder"
          ],
          "onStartShouldSetResponder":[
             "Function bound scrollResponderHandleStartShouldSetResponder"
          ],
          "onStartShouldSetResponderCapture":[
             "Function bound scrollResponderHandleStartShouldSetResponderCapture"
          ],
          "onTouchCancel":[
             "Function bound scrollResponderHandleTouchCancel"
          ],
          "onTouchEnd":[
             "Function bound scrollResponderHandleTouchEnd"
          ],
          "onTouchMove":[
             "Function bound scrollResponderHandleTouchMove"
          ],
          "onTouchStart":[
             "Function bound scrollResponderHandleTouchStart"
          ],
          "pagingEnabled":true,
          "scrollBarThumbImage":null,
          "scrollEventThrottle":"undefined",
          "scrollViewRef":null,
          "sendMomentumEvents":false,
          "showsHorizontalScrollIndicator":false,
          "snapToEnd":true,
          "snapToInterval":411.42857142857144,
          "snapToStart":true,
          "style":[
             "Array"
          ]
       },
       "memoizedState":null,
       "mode":8,
       "nextEffect":null,
       "pendingProps":{
          "DEPRECATED_sendUpdatedChildFrames":false,
          "alwaysBounceHorizontal":true,
          "alwaysBounceVertical":false,
          "children":"<AndroidHorizontalScrollContentView … />",
          "decelerationRate":0.9,
          "horizontal":true,
          "onContentSizeChange":null,
          "onLayout":[
             "Function anonymous"
          ],
          "onMomentumScrollBegin":[
             "Function bound scrollResponderHandleMomentumScrollBegin"
          ],
          "onMomentumScrollEnd":[
             "Function bound scrollResponderHandleMomentumScrollEnd"
          ],
          "onResponderGrant":[
             "Function bound scrollResponderHandleResponderGrant"
          ],
          "onResponderReject":[
             "Function bound scrollResponderHandleResponderReject"
          ],
          "onResponderRelease":[
             "Function bound scrollResponderHandleResponderRelease"
          ],
          "onResponderTerminationRequest":[
             "Function bound scrollResponderHandleTerminationRequest"
          ],
          "onScroll":[
             "Function anonymous"
          ],
          "onScrollBeginDrag":[
             "Function bound scrollResponderHandleScrollBeginDrag"
          ],
          "onScrollEndDrag":[
             "Function bound scrollResponderHandleScrollEndDrag"
          ],
          "onScrollShouldSetResponder":[
             "Function bound scrollResponderHandleScrollShouldSetResponder"
          ],
          "onStartShouldSetResponder":[
             "Function bound scrollResponderHandleStartShouldSetResponder"
          ],
          "onStartShouldSetResponderCapture":[
             "Function bound scrollResponderHandleStartShouldSetResponderCapture"
          ],
          "onTouchCancel":[
             "Function bound scrollResponderHandleTouchCancel"
          ],
          "onTouchEnd":[
             "Function bound scrollResponderHandleTouchEnd"
          ],
          "onTouchMove":[
             "Function bound scrollResponderHandleTouchMove"
          ],
          "onTouchStart":[
             "Function bound scrollResponderHandleTouchStart"
          ],
          "pagingEnabled":true,
          "scrollBarThumbImage":null,
          "scrollEventThrottle":"undefined",
          "scrollViewRef":null,
          "sendMomentumEvents":false,
          "showsHorizontalScrollIndicator":false,
          "snapToEnd":true,
          "snapToInterval":411.42857142857144,
          "snapToStart":true,
          "style":[
             "Array"
          ]
       },
       "ref":[
          "Function forwardRef"
       ],
       "return":{
          "_debugHookTypes":null,
          "_debugID":9321,
          "_debugIsCurrentlyTiming":false,
          "_debugNeedsRemount":false,
          "_debugOwner":[
             "FiberNode"
          ],
          "_debugSource":[
             "Object"
          ],
          "actualDuration":157,
          "actualStartTime":28249,
          "alternate":[
             "FiberNode"
          ],
          "child":[
             "Circular"
          ],
          "childExpirationTime":0,
          "dependencies":null,
          "effectTag":5,
          "elementType":[
             "Function ScrollView"
          ],
          "expirationTime":0,
          "firstEffect":[
             "FiberNode"
          ],
          "index":0,
          "key":null,
          "lastEffect":[
             "Circular"
          ],
          "memoizedProps":[
             "Object"
          ],
          "memoizedState":[
             "Object"
          ],
          "mode":8,
          "nextEffect":null,
          "pendingProps":[
             "Object"
          ],
          "ref":null,
          "return":[
             "FiberNode"
          ],
          "selfBaseDuration":5,
          "sibling":null,
          "stateNode":[
             "ScrollView"
          ],
          "tag":1,
          "treeBaseDuration":63,
          "type":[
             "Function ScrollView"
          ],
          "updateQueue":[
             "Object"
          ]
       },
       "selfBaseDuration":0,
       "sibling":null,
       "stateNode":{
          "_children":[
             "Array"
          ],
          "_internalFiberInstanceHandleDEV":[
             "Circular"
          ],
          "_nativeTag":847,
          "flashScrollIndicators":[
             "Function anonymous"
          ],
          "getInnerViewNode":[
             "Function getInnerViewNode"
          ],
          "getInnerViewRef":[
             "Function getInnerViewRef"
          ],
          "getNativeScrollRef":[
             "Function anonymous"
          ],
          "getScrollResponder":[
             "Function anonymous"
          ],
          "getScrollableNode":[
             "Function anonymous"
          ],
          "scrollResponderScrollNativeHandleToKeyboard":[
             "Function bound scrollResponderScrollNativeHandleToKeyboard"
          ],
          "scrollResponderZoomTo":[
             "Function bound scrollResponderZoomTo"
          ],
          "scrollTo":[
             "Function anonymous"
          ],
          "scrollToEnd":[
             "Function anonymous"
          ],
          "viewConfig":[
             "Object"
          ]
       },
       "tag":5,
       "treeBaseDuration":58,
       "type":"AndroidHorizontalScrollView",
       "updateQueue":null
    },
    "_dispatchListeners":[
       "Function anonymous"
    ],
    "_targetInst":{
       "_debugHookTypes":null,
       "_debugID":9323,
       "_debugIsCurrentlyTiming":false,
       "_debugNeedsRemount":false,
       "_debugOwner":{
          "_debugHookTypes":null,
          "_debugID":9321,
          "_debugIsCurrentlyTiming":false,
          "_debugNeedsRemount":false,
          "_debugOwner":[
             "FiberNode"
          ],
          "_debugSource":[
             "Object"
          ],
          "actualDuration":157,
          "actualStartTime":28249,
          "alternate":[
             "FiberNode"
          ],
          "child":[
             "Circular"
          ],
          "childExpirationTime":0,
          "dependencies":null,
          "effectTag":5,
          "elementType":[
             "Function ScrollView"
          ],
          "expirationTime":0,
          "firstEffect":[
             "FiberNode"
          ],
          "index":0,
          "key":null,
          "lastEffect":[
             "Circular"
          ],
          "memoizedProps":[
             "Object"
          ],
          "memoizedState":[
             "Object"
          ],
          "mode":8,
          "nextEffect":null,
          "pendingProps":[
             "Object"
          ],
          "ref":null,
          "return":[
             "FiberNode"
          ],
          "selfBaseDuration":5,
          "sibling":null,
          "stateNode":[
             "ScrollView"
          ],
          "tag":1,
          "treeBaseDuration":63,
          "type":[
             "Function ScrollView"
          ],
          "updateQueue":[
             "Object"
          ]
       },
       "_debugSource":{
          "columnNumber":7,
          "fileName":"C:\\Users\\Dominique\\Documents\\dev-l\\TaxiApp_David\\Experiments\\TC_experience_2020\\Map\\node_modules\\react-native\\Libraries\\Components\\ScrollView\\ScrollView.js",
          "lineNumber":1260
       },
       "actualDuration":152,
       "actualStartTime":28254,
       "alternate":{
          "_debugHookTypes":null,
          "_debugID":9323,
          "_debugIsCurrentlyTiming":false,
          "_debugNeedsRemount":false,
          "_debugOwner":[
             "FiberNode"
          ],
          "_debugSource":[
             "Object"
          ],
          "actualDuration":43,
          "actualStartTime":103312,
          "alternate":[
             "Circular"
          ],
          "child":[
             "FiberNode"
          ],
          "childExpirationTime":0,
          "dependencies":null,
          "effectTag":4,
          "elementType":"AndroidHorizontalScrollView",
          "expirationTime":0,
          "firstEffect":[
             "FiberNode"
          ],
          "index":0,
          "key":null,
          "lastEffect":[
             "FiberNode"
          ],
          "memoizedProps":[
             "Object"
          ],
          "memoizedState":null,
          "mode":8,
          "nextEffect":null,
          "pendingProps":[
             "Object"
          ],
          "ref":[
             "Function forwardRef"
          ],
          "return":[
             "FiberNode"
          ],
          "selfBaseDuration":0,
          "sibling":null,
          "stateNode":[
             "ReactNativeFiberHostComponent"
          ],
          "tag":5,
          "treeBaseDuration":43,
          "type":"AndroidHorizontalScrollView",
          "updateQueue":null
       },
       "child":{
          "_debugHookTypes":null,
          "_debugID":9325,
          "_debugIsCurrentlyTiming":false,
          "_debugNeedsRemount":false,
          "_debugOwner":[
             "FiberNode"
          ],
          "_debugSource":[
             "Object"
          ],
          "actualDuration":143,
          "actualStartTime":28254,
          "alternate":[
             "FiberNode"
          ],
          "child":[
             "FiberNode"
          ],
          "childExpirationTime":0,
          "dependencies":null,
          "effectTag":128,
          "elementType":"AndroidHorizontalScrollContentView",
          "expirationTime":0,
          "firstEffect":[
             "FiberNode"
          ],
          "index":0,
          "key":null,
          "lastEffect":[
             "FiberNode"
          ],
          "memoizedProps":[
             "Object"
          ],
          "memoizedState":null,
          "mode":8,
          "nextEffect":null,
          "pendingProps":[
             "Object"
          ],
          "ref":[
             "Function forwardRef"
          ],
          "return":[
             "Circular"
          ],
          "selfBaseDuration":0,
          "sibling":null,
          "stateNode":[
             "ReactNativeFiberHostComponent"
          ],
          "tag":5,
          "treeBaseDuration":58,
          "type":"AndroidHorizontalScrollContentView",
          "updateQueue":null
       },
       "childExpirationTime":0,
       "dependencies":null,
       "effectTag":128,
       "elementType":"AndroidHorizontalScrollView",
       "expirationTime":0,
       "firstEffect":{
          "_debugHookTypes":null,
          "_debugID":9365,
          "_debugIsCurrentlyTiming":false,
          "_debugNeedsRemount":false,
          "_debugOwner":[
             "FiberNode"
          ],
          "_debugSource":[
             "Object"
          ],
          "actualDuration":25,
          "actualStartTime":28261,
          "alternate":[
             "FiberNode"
          ],
          "child":[
             "FiberNode"
          ],
          "childExpirationTime":0,
          "dependencies":null,
          "effectTag":128,
          "elementType":"RCTView",
          "expirationTime":0,
          "firstEffect":null,
          "index":0,
          "key":null,
          "lastEffect":null,
          "memoizedProps":[
             "Object"
          ],
          "memoizedState":null,
          "mode":8,
          "nextEffect":null,
          "pendingProps":[
             "Object"
          ],
          "ref":[
             "Function forwardRef"
          ],
          "return":[
             "FiberNode"
          ],
          "selfBaseDuration":0,
          "sibling":null,
          "stateNode":[
             "ReactNativeFiberHostComponent"
          ],
          "tag":5,
          "treeBaseDuration":9,
          "type":"RCTView",
          "updateQueue":null
       },
       "index":0,
       "key":null,
       "lastEffect":{
          "_debugHookTypes":null,
          "_debugID":9325,
          "_debugIsCurrentlyTiming":false,
          "_debugNeedsRemount":false,
          "_debugOwner":[
             "FiberNode"
          ],
          "_debugSource":[
             "Object"
          ],
          "actualDuration":143,
          "actualStartTime":28254,
          "alternate":[
             "FiberNode"
          ],
          "child":[
             "FiberNode"
          ],
          "childExpirationTime":0,
          "dependencies":null,
          "effectTag":128,
          "elementType":"AndroidHorizontalScrollContentView",
          "expirationTime":0,
          "firstEffect":[
             "FiberNode"
          ],
          "index":0,
          "key":null,
          "lastEffect":[
             "FiberNode"
          ],
          "memoizedProps":[
             "Object"
          ],
          "memoizedState":null,
          "mode":8,
          "nextEffect":null,
          "pendingProps":[
             "Object"
          ],
          "ref":[
             "Function forwardRef"
          ],
          "return":[
             "Circular"
          ],
          "selfBaseDuration":0,
          "sibling":null,
          "stateNode":[
             "ReactNativeFiberHostComponent"
          ],
          "tag":5,
          "treeBaseDuration":58,
          "type":"AndroidHorizontalScrollContentView",
          "updateQueue":null
       },
       "memoizedProps":{
          "DEPRECATED_sendUpdatedChildFrames":false,
          "alwaysBounceHorizontal":true,
          "alwaysBounceVertical":false,
          "children":"<AndroidHorizontalScrollContentView … />",
          "decelerationRate":0.9,
          "horizontal":true,
          "onContentSizeChange":null,
          "onLayout":[
             "Function anonymous"
          ],
          "onMomentumScrollBegin":[
             "Function bound scrollResponderHandleMomentumScrollBegin"
          ],
          "onMomentumScrollEnd":[
             "Function bound scrollResponderHandleMomentumScrollEnd"
          ],
          "onResponderGrant":[
             "Function bound scrollResponderHandleResponderGrant"
          ],
          "onResponderReject":[
             "Function bound scrollResponderHandleResponderReject"
          ],
          "onResponderRelease":[
             "Function bound scrollResponderHandleResponderRelease"
          ],
          "onResponderTerminationRequest":[
             "Function bound scrollResponderHandleTerminationRequest"
          ],
          "onScroll":[
             "Function anonymous"
          ],
          "onScrollBeginDrag":[
             "Function bound scrollResponderHandleScrollBeginDrag"
          ],
          "onScrollEndDrag":[
             "Function bound scrollResponderHandleScrollEndDrag"
          ],
          "onScrollShouldSetResponder":[
             "Function bound scrollResponderHandleScrollShouldSetResponder"
          ],
          "onStartShouldSetResponder":[
             "Function bound scrollResponderHandleStartShouldSetResponder"
          ],
          "onStartShouldSetResponderCapture":[
             "Function bound scrollResponderHandleStartShouldSetResponderCapture"
          ],
          "onTouchCancel":[
             "Function bound scrollResponderHandleTouchCancel"
          ],
          "onTouchEnd":[
             "Function bound scrollResponderHandleTouchEnd"
          ],
          "onTouchMove":[
             "Function bound scrollResponderHandleTouchMove"
          ],
          "onTouchStart":[
             "Function bound scrollResponderHandleTouchStart"
          ],
          "pagingEnabled":true,
          "scrollBarThumbImage":null,
          "scrollEventThrottle":"undefined",
          "scrollViewRef":null,
          "sendMomentumEvents":false,
          "showsHorizontalScrollIndicator":false,
          "snapToEnd":true,
          "snapToInterval":411.42857142857144,
          "snapToStart":true,
          "style":[
             "Array"
          ]
       },
       "memoizedState":null,
       "mode":8,
       "nextEffect":null,
       "pendingProps":{
          "DEPRECATED_sendUpdatedChildFrames":false,
          "alwaysBounceHorizontal":true,
          "alwaysBounceVertical":false,
          "children":"<AndroidHorizontalScrollContentView … />",
          "decelerationRate":0.9,
          "horizontal":true,
          "onContentSizeChange":null,
          "onLayout":[
             "Function anonymous"
          ],
          "onMomentumScrollBegin":[
             "Function bound scrollResponderHandleMomentumScrollBegin"
          ],
          "onMomentumScrollEnd":[
             "Function bound scrollResponderHandleMomentumScrollEnd"
          ],
          "onResponderGrant":[
             "Function bound scrollResponderHandleResponderGrant"
          ],
          "onResponderReject":[
             "Function bound scrollResponderHandleResponderReject"
          ],
          "onResponderRelease":[
             "Function bound scrollResponderHandleResponderRelease"
          ],
          "onResponderTerminationRequest":[
             "Function bound scrollResponderHandleTerminationRequest"
          ],
          "onScroll":[
             "Function anonymous"
          ],
          "onScrollBeginDrag":[
             "Function bound scrollResponderHandleScrollBeginDrag"
          ],
          "onScrollEndDrag":[
             "Function bound scrollResponderHandleScrollEndDrag"
          ],
          "onScrollShouldSetResponder":[
             "Function bound scrollResponderHandleScrollShouldSetResponder"
          ],
          "onStartShouldSetResponder":[
             "Function bound scrollResponderHandleStartShouldSetResponder"
          ],
          "onStartShouldSetResponderCapture":[
             "Function bound scrollResponderHandleStartShouldSetResponderCapture"
          ],
          "onTouchCancel":[
             "Function bound scrollResponderHandleTouchCancel"
          ],
          "onTouchEnd":[
             "Function bound scrollResponderHandleTouchEnd"
          ],
          "onTouchMove":[
             "Function bound scrollResponderHandleTouchMove"
          ],
          "onTouchStart":[
             "Function bound scrollResponderHandleTouchStart"
          ],
          "pagingEnabled":true,
          "scrollBarThumbImage":null,
          "scrollEventThrottle":"undefined",
          "scrollViewRef":null,
          "sendMomentumEvents":false,
          "showsHorizontalScrollIndicator":false,
          "snapToEnd":true,
          "snapToInterval":411.42857142857144,
          "snapToStart":true,
          "style":[
             "Array"
          ]
       },
       "ref":[
          "Function forwardRef"
       ],
       "return":{
          "_debugHookTypes":null,
          "_debugID":9321,
          "_debugIsCurrentlyTiming":false,
          "_debugNeedsRemount":false,
          "_debugOwner":[
             "FiberNode"
          ],
          "_debugSource":[
             "Object"
          ],
          "actualDuration":157,
          "actualStartTime":28249,
          "alternate":[
             "FiberNode"
          ],
          "child":[
             "Circular"
          ],
          "childExpirationTime":0,
          "dependencies":null,
          "effectTag":5,
          "elementType":[
             "Function ScrollView"
          ],
          "expirationTime":0,
          "firstEffect":[
             "FiberNode"
          ],
          "index":0,
          "key":null,
          "lastEffect":[
             "Circular"
          ],
          "memoizedProps":[
             "Object"
          ],
          "memoizedState":[
             "Object"
          ],
          "mode":8,
          "nextEffect":null,
          "pendingProps":[
             "Object"
          ],
          "ref":null,
          "return":[
             "FiberNode"
          ],
          "selfBaseDuration":5,
          "sibling":null,
          "stateNode":[
             "ScrollView"
          ],
          "tag":1,
          "treeBaseDuration":63,
          "type":[
             "Function ScrollView"
          ],
          "updateQueue":[
             "Object"
          ]
       },
       "selfBaseDuration":0,
       "sibling":null,
       "stateNode":{
          "_children":[
             "Array"
          ],
          "_internalFiberInstanceHandleDEV":[
             "Circular"
          ],
          "_nativeTag":847,
          "flashScrollIndicators":[
             "Function anonymous"
          ],
          "getInnerViewNode":[
             "Function getInnerViewNode"
          ],
          "getInnerViewRef":[
             "Function getInnerViewRef"
          ],
          "getNativeScrollRef":[
             "Function anonymous"
          ],
          "getScrollResponder":[
             "Function anonymous"
          ],
          "getScrollableNode":[
             "Function anonymous"
          ],
          "scrollResponderScrollNativeHandleToKeyboard":[
             "Function bound scrollResponderScrollNativeHandleToKeyboard"
          ],
          "scrollResponderZoomTo":[
             "Function bound scrollResponderZoomTo"
          ],
          "scrollTo":[
             "Function anonymous"
          ],
          "scrollToEnd":[
             "Function anonymous"
          ],
          "viewConfig":[
             "Object"
          ]
       },
       "tag":5,
       "treeBaseDuration":58,
       "type":"AndroidHorizontalScrollView",
       "updateQueue":null
    },
    "bubbles":"undefined",
    "cancelable":"undefined",
    "currentTarget":{
       "_children":[
          [
             "ReactNativeFiberHostComponent"
          ]
       ],
       "_internalFiberInstanceHandleDEV":{
          "_debugHookTypes":null,
          "_debugID":9323,
          "_debugIsCurrentlyTiming":false,
          "_debugNeedsRemount":false,
          "_debugOwner":[
             "FiberNode"
          ],
          "_debugSource":[
             "Object"
          ],
          "actualDuration":152,
          "actualStartTime":28254,
          "alternate":[
             "FiberNode"
          ],
          "child":[
             "FiberNode"
          ],
          "childExpirationTime":0,
          "dependencies":null,
          "effectTag":128,
          "elementType":"AndroidHorizontalScrollView",
          "expirationTime":0,
          "firstEffect":[
             "FiberNode"
          ],
          "index":0,
          "key":null,
          "lastEffect":[
             "FiberNode"
          ],
          "memoizedProps":[
             "Object"
          ],
          "memoizedState":null,
          "mode":8,
          "nextEffect":null,
          "pendingProps":[
             "Object"
          ],
          "ref":[
             "Function forwardRef"
          ],
          "return":[
             "FiberNode"
          ],
          "selfBaseDuration":0,
          "sibling":null,
          "stateNode":[
             "Circular"
          ],
          "tag":5,
          "treeBaseDuration":58,
          "type":"AndroidHorizontalScrollView",
          "updateQueue":null
       },
       "_nativeTag":847,
       "flashScrollIndicators":[
          "Function anonymous"
       ],
       "getInnerViewNode":[
          "Function getInnerViewNode"
       ],
       "getInnerViewRef":[
          "Function getInnerViewRef"
       ],
       "getNativeScrollRef":[
          "Function anonymous"
       ],
       "getScrollResponder":[
          "Function anonymous"
       ],
       "getScrollableNode":[
          "Function anonymous"
       ],
       "scrollResponderScrollNativeHandleToKeyboard":[
          "Function bound scrollResponderScrollNativeHandleToKeyboard"
       ],
       "scrollResponderZoomTo":[
          "Function bound scrollResponderZoomTo"
       ],
       "scrollTo":[
          "Function anonymous"
       ],
       "scrollToEnd":[
          "Function anonymous"
       ],
       "viewConfig":{
          "NativeProps":[
             "Object"
          ],
          "bubblingEventTypes":"undefined",
          "directEventTypes":[
             "Object"
          ],
          "uiViewClassName":"AndroidHorizontalScrollView",
          "validAttributes":[
             "Object"
          ]
       }
    },
    "defaultPrevented":"undefined",
    "dispatchConfig":{
       "registrationName":"onScroll"
    },
    "eventPhase":"undefined",
    "isDefaultPrevented":[
       "Function functionThatReturnsFalse"
    ],
    "isPropagationStopped":[
       "Function functionThatReturnsFalse"
    ],
    "isTrusted":"undefined",
    "nativeEvent":{
       "contentInset":{
          "bottom":0,
          "left":0,
          "right":0,
          "top":0
       },
       "contentOffset":{
          "x":335.23809814453125,
          "y":0
       },
       "contentSize":{
          "height":195.8095245361328,
          "width":731.8095092773438
       },
       "layoutMeasurement":{
          "height":195.8095245361328,
          "width":368
       },
       "responderIgnoreScroll":true,
       "target":847,
       "velocity":{
          "x":3.117647171020508,
          "y":0
       }
    },
    "target":{
       "_children":[
          [
             "ReactNativeFiberHostComponent"
          ]
       ],
       "_internalFiberInstanceHandleDEV":{
          "_debugHookTypes":null,
          "_debugID":9323,
          "_debugIsCurrentlyTiming":false,
          "_debugNeedsRemount":false,
          "_debugOwner":[
             "FiberNode"
          ],
          "_debugSource":[
             "Object"
          ],
          "actualDuration":152,
          "actualStartTime":28254,
          "alternate":[
             "FiberNode"
          ],
          "child":[
             "FiberNode"
          ],
          "childExpirationTime":0,
          "dependencies":null,
          "effectTag":128,
          "elementType":"AndroidHorizontalScrollView",
          "expirationTime":0,
          "firstEffect":[
             "FiberNode"
          ],
          "index":0,
          "key":null,
          "lastEffect":[
             "FiberNode"
          ],
          "memoizedProps":[
             "Object"
          ],
          "memoizedState":null,
          "mode":8,
          "nextEffect":null,
          "pendingProps":[
             "Object"
          ],
          "ref":[
             "Function forwardRef"
          ],
          "return":[
             "FiberNode"
          ],
          "selfBaseDuration":0,
          "sibling":null,
          "stateNode":[
             "Circular"
          ],
          "tag":5,
          "treeBaseDuration":58,
          "type":"AndroidHorizontalScrollView",
          "updateQueue":null
       },
       "_nativeTag":847,
       "flashScrollIndicators":[
          "Function anonymous"
       ],
       "getInnerViewNode":[
          "Function getInnerViewNode"
       ],
       "getInnerViewRef":[
          "Function getInnerViewRef"
       ],
       "getNativeScrollRef":[
          "Function anonymous"
       ],
       "getScrollResponder":[
          "Function anonymous"
       ],
       "getScrollableNode":[
          "Function anonymous"
       ],
       "scrollResponderScrollNativeHandleToKeyboard":[
          "Function bound scrollResponderScrollNativeHandleToKeyboard"
       ],
       "scrollResponderZoomTo":[
          "Function bound scrollResponderZoomTo"
       ],
       "scrollTo":[
          "Function anonymous"
       ],
       "scrollToEnd":[
          "Function anonymous"
       ],
       "viewConfig":{
          "NativeProps":[
             "Object"
          ],
          "bubblingEventTypes":"undefined",
          "directEventTypes":[
             "Object"
          ],
          "uiViewClassName":"AndroidHorizontalScrollView",
          "validAttributes":[
             "Object"
          ]
       }
    },
    "timeStamp":1606209540059,
    "type":"undefined"
 }



 {
    "_children":[
       {
          "_children":[
             "Array"
          ],
          "_internalFiberInstanceHandleDEV":[
             "FiberNode"
          ],
          "_nativeTag":1169,
          "viewConfig":[
             "Object"
          ]
       }
    ],
    "_internalFiberInstanceHandleDEV":{
       "_debugHookTypes":null,
       "_debugID":8736,
       "_debugIsCurrentlyTiming":false,
       "_debugNeedsRemount":false,
       "_debugOwner":{
          "_debugHookTypes":null,
          "_debugID":8734,
          "_debugIsCurrentlyTiming":false,
          "_debugNeedsRemount":false,
          "_debugOwner":[
             "FiberNode"
          ],
          "_debugSource":[
             "Object"
          ],
          "actualDuration":264,
          "actualStartTime":44700,
          "alternate":null,
          "child":[
             "Circular"
          ],
          "childExpirationTime":0,
          "dependencies":null,
          "effectTag":5,
          "elementType":[
             "Function ScrollView"
          ],
          "expirationTime":0,
          "firstEffect":[
             "FiberNode"
          ],
          "index":0,
          "key":null,
          "lastEffect":[
             "Circular"
          ],
          "memoizedProps":[
             "Object"
          ],
          "memoizedState":[
             "Object"
          ],
          "mode":8,
          "nextEffect":null,
          "pendingProps":[
             "Object"
          ],
          "ref":null,
          "return":[
             "FiberNode"
          ],
          "selfBaseDuration":3,
          "sibling":null,
          "stateNode":[
             "ScrollView"
          ],
          "tag":1,
          "treeBaseDuration":110,
          "type":[
             "Function ScrollView"
          ],
          "updateQueue":[
             "Object"
          ]
       },
       "_debugSource":{
          "columnNumber":7,
          "fileName":"C:\\Users\\Dominique\\Documents\\dev-l\\TaxiApp_David\\Experiments\\TC_experience_2020\\Map\\node_modules\\react-native\\Libraries\\Components\\ScrollView\\ScrollView.js",
          "lineNumber":1260
       },
       "actualDuration":261,
       "actualStartTime":44703,
       "alternate":null,
       "child":{
          "_debugHookTypes":null,
          "_debugID":8738,
          "_debugIsCurrentlyTiming":false,
          "_debugNeedsRemount":false,
          "_debugOwner":[
             "FiberNode"
          ],
          "_debugSource":[
             "Object"
          ],
          "actualDuration":257,
          "actualStartTime":44703,
          "alternate":null,
          "child":[
             "FiberNode"
          ],
          "childExpirationTime":0,
          "dependencies":null,
          "effectTag":128,
          "elementType":"AndroidHorizontalScrollContentView",
          "expirationTime":0,
          "firstEffect":[
             "FiberNode"
          ],
          "index":0,
          "key":null,
          "lastEffect":[
             "FiberNode"
          ],
          "memoizedProps":[
             "Object"
          ],
          "memoizedState":null,
          "mode":8,
          "nextEffect":null,
          "pendingProps":[
             "Object"
          ],
          "ref":[
             "Function forwardRef"
          ],
          "return":[
             "Circular"
          ],
          "selfBaseDuration":1,
          "sibling":null,
          "stateNode":[
             "ReactNativeFiberHostComponent"
          ],
          "tag":5,
          "treeBaseDuration":107,
          "type":"AndroidHorizontalScrollContentView",
          "updateQueue":null
       },
       "childExpirationTime":0,
       "dependencies":null,
       "effectTag":128,
       "elementType":"AndroidHorizontalScrollView",
       "expirationTime":0,
       "firstEffect":{
          "_debugHookTypes":null,
          "_debugID":8779,
          "_debugIsCurrentlyTiming":false,
          "_debugNeedsRemount":false,
          "_debugOwner":[
             "FiberNode"
          ],
          "_debugSource":[
             "Object"
          ],
          "actualDuration":32,
          "actualStartTime":44715,
          "alternate":null,
          "child":[
             "FiberNode"
          ],
          "childExpirationTime":0,
          "dependencies":null,
          "effectTag":128,
          "elementType":"RCTView",
          "expirationTime":0,
          "firstEffect":null,
          "index":0,
          "key":null,
          "lastEffect":null,
          "memoizedProps":[
             "Object"
          ],
          "memoizedState":null,
          "mode":8,
          "nextEffect":null,
          "pendingProps":[
             "Object"
          ],
          "ref":[
             "Function forwardRef"
          ],
          "return":[
             "FiberNode"
          ],
          "selfBaseDuration":1,
          "sibling":null,
          "stateNode":[
             "ReactNativeFiberHostComponent"
          ],
          "tag":5,
          "treeBaseDuration":8,
          "type":"RCTView",
          "updateQueue":null
       },
       "index":0,
       "key":null,
       "lastEffect":{
          "_debugHookTypes":null,
          "_debugID":8738,
          "_debugIsCurrentlyTiming":false,
          "_debugNeedsRemount":false,
          "_debugOwner":[
             "FiberNode"
          ],
          "_debugSource":[
             "Object"
          ],
          "actualDuration":257,
          "actualStartTime":44703,
          "alternate":null,
          "child":[
             "FiberNode"
          ],
          "childExpirationTime":0,
          "dependencies":null,
          "effectTag":128,
          "elementType":"AndroidHorizontalScrollContentView",
          "expirationTime":0,
          "firstEffect":[
             "FiberNode"
          ],
          "index":0,
          "key":null,
          "lastEffect":[
             "FiberNode"
          ],
          "memoizedProps":[
             "Object"
          ],
          "memoizedState":null,
          "mode":8,
          "nextEffect":null,
          "pendingProps":[
             "Object"
          ],
          "ref":[
             "Function forwardRef"
          ],
          "return":[
             "Circular"
          ],
          "selfBaseDuration":1,
          "sibling":null,
          "stateNode":[
             "ReactNativeFiberHostComponent"
          ],
          "tag":5,
          "treeBaseDuration":107,
          "type":"AndroidHorizontalScrollContentView",
          "updateQueue":null
       },
       "memoizedProps":{
          "DEPRECATED_sendUpdatedChildFrames":false,
          "alwaysBounceHorizontal":true,
          "alwaysBounceVertical":false,
          "children":"<AndroidHorizontalScrollContentView … />",
          "decelerationRate":0.9,
          "horizontal":true,
          "onContentSizeChange":null,
          "onLayout":[
             "Function anonymous"
          ],
          "onMomentumScrollBegin":[
             "Function bound scrollResponderHandleMomentumScrollBegin"
          ],
          "onMomentumScrollEnd":[
             "Function bound scrollResponderHandleMomentumScrollEnd"
          ],
          "onResponderGrant":[
             "Function bound scrollResponderHandleResponderGrant"
          ],
          "onResponderReject":[
             "Function bound scrollResponderHandleResponderReject"
          ],
          "onResponderRelease":[
             "Function bound scrollResponderHandleResponderRelease"
          ],
          "onResponderTerminationRequest":[
             "Function bound scrollResponderHandleTerminationRequest"
          ],
          "onScroll":[
             "Function anonymous"
          ],
          "onScrollBeginDrag":[
             "Function bound scrollResponderHandleScrollBeginDrag"
          ],
          "onScrollEndDrag":[
             "Function bound scrollResponderHandleScrollEndDrag"
          ],
          "onScrollShouldSetResponder":[
             "Function bound scrollResponderHandleScrollShouldSetResponder"
          ],
          "onStartShouldSetResponder":[
             "Function bound scrollResponderHandleStartShouldSetResponder"
          ],
          "onStartShouldSetResponderCapture":[
             "Function bound scrollResponderHandleStartShouldSetResponderCapture"
          ],
          "onTouchCancel":[
             "Function bound scrollResponderHandleTouchCancel"
          ],
          "onTouchEnd":[
             "Function bound scrollResponderHandleTouchEnd"
          ],
          "onTouchMove":[
             "Function bound scrollResponderHandleTouchMove"
          ],
          "onTouchStart":[
             "Function bound scrollResponderHandleTouchStart"
          ],
          "pagingEnabled":true,
          "scrollBarThumbImage":null,
          "scrollEventThrottle":"undefined",
          "scrollViewRef":[
             "Function ref"
          ],
          "sendMomentumEvents":false,
          "showsHorizontalScrollIndicator":false,
          "snapToEnd":true,
          "snapToInterval":411.42857142857144,
          "snapToStart":true,
          "style":[
             "Array"
          ]
       },
       "memoizedState":null,
       "mode":8,
       "nextEffect":null,
       "pendingProps":{
          "DEPRECATED_sendUpdatedChildFrames":false,
          "alwaysBounceHorizontal":true,
          "alwaysBounceVertical":false,
          "children":"<AndroidHorizontalScrollContentView … />",
          "decelerationRate":0.9,
          "horizontal":true,
          "onContentSizeChange":null,
          "onLayout":[
             "Function anonymous"
          ],
          "onMomentumScrollBegin":[
             "Function bound scrollResponderHandleMomentumScrollBegin"
          ],
          "onMomentumScrollEnd":[
             "Function bound scrollResponderHandleMomentumScrollEnd"
          ],
          "onResponderGrant":[
             "Function bound scrollResponderHandleResponderGrant"
          ],
          "onResponderReject":[
             "Function bound scrollResponderHandleResponderReject"
          ],
          "onResponderRelease":[
             "Function bound scrollResponderHandleResponderRelease"
          ],
          "onResponderTerminationRequest":[
             "Function bound scrollResponderHandleTerminationRequest"
          ],
          "onScroll":[
             "Function anonymous"
          ],
          "onScrollBeginDrag":[
             "Function bound scrollResponderHandleScrollBeginDrag"
          ],
          "onScrollEndDrag":[
             "Function bound scrollResponderHandleScrollEndDrag"
          ],
          "onScrollShouldSetResponder":[
             "Function bound scrollResponderHandleScrollShouldSetResponder"
          ],
          "onStartShouldSetResponder":[
             "Function bound scrollResponderHandleStartShouldSetResponder"
          ],
          "onStartShouldSetResponderCapture":[
             "Function bound scrollResponderHandleStartShouldSetResponderCapture"
          ],
          "onTouchCancel":[
             "Function bound scrollResponderHandleTouchCancel"
          ],
          "onTouchEnd":[
             "Function bound scrollResponderHandleTouchEnd"
          ],
          "onTouchMove":[
             "Function bound scrollResponderHandleTouchMove"
          ],
          "onTouchStart":[
             "Function bound scrollResponderHandleTouchStart"
          ],
          "pagingEnabled":true,
          "scrollBarThumbImage":null,
          "scrollEventThrottle":"undefined",
          "scrollViewRef":[
             "Function ref"
          ],
          "sendMomentumEvents":false,
          "showsHorizontalScrollIndicator":false,
          "snapToEnd":true,
          "snapToInterval":411.42857142857144,
          "snapToStart":true,
          "style":[
             "Array"
          ]
       },
       "ref":[
          "Function forwardRef"
       ],
       "return":{
          "_debugHookTypes":null,
          "_debugID":8734,
          "_debugIsCurrentlyTiming":false,
          "_debugNeedsRemount":false,
          "_debugOwner":[
             "FiberNode"
          ],
          "_debugSource":[
             "Object"
          ],
          "actualDuration":264,
          "actualStartTime":44700,
          "alternate":null,
          "child":[
             "Circular"
          ],
          "childExpirationTime":0,
          "dependencies":null,
          "effectTag":5,
          "elementType":[
             "Function ScrollView"
          ],
          "expirationTime":0,
          "firstEffect":[
             "FiberNode"
          ],
          "index":0,
          "key":null,
          "lastEffect":[
             "Circular"
          ],
          "memoizedProps":[
             "Object"
          ],
          "memoizedState":[
             "Object"
          ],
          "mode":8,
          "nextEffect":null,
          "pendingProps":[
             "Object"
          ],
          "ref":null,
          "return":[
             "FiberNode"
          ],
          "selfBaseDuration":3,
          "sibling":null,
          "stateNode":[
             "ScrollView"
          ],
          "tag":1,
          "treeBaseDuration":110,
          "type":[
             "Function ScrollView"
          ],
          "updateQueue":[
             "Object"
          ]
       },
       "selfBaseDuration":0,
       "sibling":null,
       "stateNode":[
          "Circular"
       ],
       "tag":5,
       "treeBaseDuration":107,
       "type":"AndroidHorizontalScrollView",
       "updateQueue":null
    },
    "_nativeTag":1173,
    "flashScrollIndicators":[
       "Function anonymous"
    ],
    "getInnerViewNode":[
       "Function getInnerViewNode"
    ],
    "getInnerViewRef":[
       "Function getInnerViewRef"
    ],
    "getNativeScrollRef":[
       "Function anonymous"
    ],
    "getScrollResponder":[
       "Function anonymous"
    ],
    "getScrollableNode":[
       "Function anonymous"
    ],
    "scrollResponderScrollNativeHandleToKeyboard":[
       "Function bound scrollResponderScrollNativeHandleToKeyboard"
    ],
    "scrollResponderZoomTo":[
       "Function bound scrollResponderZoomTo"
    ],
    "scrollTo":[
       "Function anonymous"
    ],
    "scrollToEnd":[
       "Function anonymous"
    ],
    "viewConfig":{
       "NativeProps":{
          "accessibilityActions":"Array",
          "accessibilityHint":"String",
          "accessibilityLabel":"String",
          "accessibilityLiveRegion":"String",
          "accessibilityRole":"String",
          "accessibilityState":"Map",
          "accessibilityValue":"Map",
          "alignContent":"String",
          "alignItems":"String",
          "alignSelf":"String",
          "aspectRatio":"number",
          "backgroundColor":"Color",
          "borderBottomColor":"Color",
          "borderBottomLeftRadius":"number",
          "borderBottomRightRadius":"number",
          "borderBottomWidth":"number",
          "borderColor":"Color",
          "borderEndWidth":"number",
          "borderLeftColor":"Color",
          "borderLeftWidth":"number",
          "borderRadius":"number",
          "borderRightColor":"Color",
          "borderRightWidth":"number",
          "borderStartWidth":"number",
          "borderStyle":"String",
          "borderTopColor":"Color",
          "borderTopLeftRadius":"number",
          "borderTopRightRadius":"number",
          "borderTopWidth":"number",
          "borderWidth":"number",
          "bottom":"mixed",
          "collapsable":"boolean",
          "decelerationRate":"number",
          "disableIntervalMomentum":"boolean",
          "display":"String",
          "elevation":"number",
          "end":"mixed",
          "endFillColor":"Color",
          "fadingEdgeLength":"number",
          "flex":"number",
          "flexBasis":"mixed",
          "flexDirection":"String",
          "flexGrow":"number",
          "flexShrink":"number",
          "flexWrap":"String",
          "height":"mixed",
          "importantForAccessibility":"String",
          "justifyContent":"String",
          "left":"mixed",
          "margin":"mixed",
          "marginBottom":"mixed",
          "marginEnd":"mixed",
          "marginHorizontal":"mixed",
          "marginLeft":"mixed",
          "marginRight":"mixed",
          "marginStart":"mixed",
          "marginTop":"mixed",
          "marginVertical":"mixed",
          "maxHeight":"mixed",
          "maxWidth":"mixed",
          "minHeight":"mixed",
          "minWidth":"mixed",
          "nativeID":"String",
          "nestedScrollEnabled":"boolean",
          "onLayout":"boolean",
          "opacity":"number",
          "overScrollMode":"String",
          "overflow":"String",
          "padding":"mixed",
          "paddingBottom":"mixed",
          "paddingEnd":"mixed",
          "paddingHorizontal":"mixed",
          "paddingLeft":"mixed",
          "paddingRight":"mixed",
          "paddingStart":"mixed",
          "paddingTop":"mixed",
          "paddingVertical":"mixed",
          "pagingEnabled":"boolean",
          "persistentScrollbar":"boolean",
          "position":"String",
          "removeClippedSubviews":"boolean",
          "renderToHardwareTextureAndroid":"boolean",
          "right":"mixed",
          "rotation":"number",
          "scaleX":"number",
          "scaleY":"number",
          "scrollEnabled":"boolean",
          "scrollPerfTag":"String",
          "sendMomentumEvents":"boolean",
          "showsHorizontalScrollIndicator":"boolean",
          "snapToEnd":"boolean",
          "snapToInterval":"number",
          "snapToOffsets":"Array",
          "snapToStart":"boolean",
          "start":"mixed",
          "testID":"String",
          "top":"mixed",
          "transform":"Array",
          "translateX":"number",
          "translateY":"number",
          "width":"mixed",
          "zIndex":"number"
       },
       "bubblingEventTypes":"undefined",
       "directEventTypes":{
          "topAccessibilityAction":[
             "Object"
          ]
       },
       "uiViewClassName":"AndroidHorizontalScrollView",
       "validAttributes":{
          "accessibilityActions":true,
          "accessibilityHint":true,
          "accessibilityLabel":true,
          "accessibilityLiveRegion":true,
          "accessibilityRole":true,
          "accessibilityState":true,
          "accessibilityValue":true,
          "alignContent":true,
          "alignItems":true,
          "alignSelf":true,
          "aspectRatio":true,
          "backgroundColor":[
             "Object"
          ],
          "borderBottomColor":[
             "Object"
          ],
          "borderBottomLeftRadius":true,
          "borderBottomRightRadius":true,
          "borderBottomWidth":true,
          "borderColor":[
             "Object"
          ],
          "borderEndWidth":true,
          "borderLeftColor":[
             "Object"
          ],
          "borderLeftWidth":true,
          "borderRadius":true,
          "borderRightColor":[
             "Object"
          ],
          "borderRightWidth":true,
          "borderStartWidth":true,
          "borderStyle":true,
          "borderTopColor":[
             "Object"
          ],
          "borderTopLeftRadius":true,
          "borderTopRightRadius":true,
          "borderTopWidth":true,
          "borderWidth":true,
          "bottom":true,
          "collapsable":true,
          "decelerationRate":true,
          "disableIntervalMomentum":true,
          "display":true,
          "elevation":true,
          "end":true,
          "endFillColor":[
             "Object"
          ],
          "fadingEdgeLength":true,
          "flex":true,
          "flexBasis":true,
          "flexDirection":true,
          "flexGrow":true,
          "flexShrink":true,
          "flexWrap":true,
          "height":true,
          "importantForAccessibility":true,
          "justifyContent":true,
          "left":true,
          "margin":true,
          "marginBottom":true,
          "marginEnd":true,
          "marginHorizontal":true,
          "marginLeft":true,
          "marginRight":true,
          "marginStart":true,
          "marginTop":true,
          "marginVertical":true,
          "maxHeight":true,
          "maxWidth":true,
          "minHeight":true,
          "minWidth":true,
          "nativeID":true,
          "nestedScrollEnabled":true,
          "onLayout":true,
          "opacity":true,
          "overScrollMode":true,
          "overflow":true,
          "padding":true,
          "paddingBottom":true,
          "paddingEnd":true,
          "paddingHorizontal":true,
          "paddingLeft":true,
          "paddingRight":true,
          "paddingStart":true,
          "paddingTop":true,
          "paddingVertical":true,
          "pagingEnabled":true,
          "persistentScrollbar":true,
          "position":true,
          "removeClippedSubviews":true,
          "renderToHardwareTextureAndroid":true,
          "right":true,
          "rotation":true,
          "scaleX":true,
          "scaleY":true,
          "scrollEnabled":true,
          "scrollPerfTag":true,
          "sendMomentumEvents":true,
          "showsHorizontalScrollIndicator":true,
          "snapToEnd":true,
          "snapToInterval":true,
          "snapToOffsets":true,
          "snapToStart":true,
          "start":true,
          "style":[
             "Object"
          ],
          "testID":true,
          "top":true,
          "transform":true,
          "translateX":true,
          "translateY":true,
          "width":true,
          "zIndex":true
       }
    }
 }